// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { VoteController } from './vote.controller.js';
import { VoteService } from './vote.service.js';

@Module({
  controllers: [VoteController],
  providers: [VoteService],
})
export class VoteModule {}
