// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBody,
  ApiBadRequestResponse,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateVoteDto } from './dto/create-vote.dto.js';
import { VoteResponseDto } from './dto/vote-response.dto.js';
import { UpdateVoteDto } from './dto/update-vote.dto.js';
import { VoteService } from './vote.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';

@ApiTags('votes')
@Controller('votes')
export class VoteController {
  constructor(private readonly voteService: VoteService) {}

  @Post()
  @ApiOperation({ operationId: 'createVote', summary: 'Create a Vote.' })
  @ApiBody({ type: CreateVoteDto })
  @ApiCreatedResponse({ type: VoteResponseDto })
  create(@Body() data: CreateVoteDto): Promise<VoteResponseDto> {
    return this.voteService.create(data);
  }

  @Get()
  @ApiOperation({ operationId: 'listVotes', summary: 'List Vote records.' })
  @ApiOkResponse({ type: VoteResponseDto, isArray: true })
  findAll(): Promise<VoteResponseDto[]> {
    return this.voteService.findAll();
  }

  @Get(':id')
  @ApiOperation({ operationId: 'getVote', summary: 'Get a Vote by ID.' })
  @ApiParam({ name: 'id', type: String, description: 'Vote ID.' })
  @ApiOkResponse({ type: VoteResponseDto })
  @ApiNotFoundResponse({ description: 'Vote not found.' })
  async findOne(@Param('id') id: string): Promise<VoteResponseDto> {
    const result = await this.voteService.findOne(id);
    if (!result) throw new NotFoundException('Vote not found.');
    return result;
  }

  @Get(':id/relations')
  @ApiOperation({
    operationId: 'listVoteRelations',
    summary: 'Query relationships associated with a Vote.',
  })
  @ApiParam({
    name: 'id',
    type: String,
    description: 'Vote ID (URL-encode slashes).',
  })
  @ApiOkResponse({ type: RelationshipResponseDto, isArray: true })
  @ApiBadRequestResponse({
    description: 'Invalid direction or equality filters.',
  })
  @ApiNotFoundResponse({ description: 'Vote not found.' })
  findRelations(
    @Param('id') id: string,
    @Query() query: RelationsQueryDto,
  ): Promise<RelationshipResponseDto[]> {
    return this.voteService.findRelations(id, query);
  }

  @Patch(':id')
  @ApiOperation({ operationId: 'updateVote', summary: 'Update a Vote.' })
  @ApiParam({ name: 'id', type: String, description: 'Vote ID.' })
  @ApiBody({ type: UpdateVoteDto })
  @ApiOkResponse({ type: VoteResponseDto })
  @ApiNotFoundResponse({ description: 'Vote not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateVoteDto,
  ): Promise<VoteResponseDto> {
    return this.voteService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ operationId: 'deleteVote', summary: 'Delete a Vote.' })
  @ApiParam({ name: 'id', type: String, description: 'Vote ID.' })
  @ApiNoContentResponse({ description: 'Vote deleted.' })
  @ApiNotFoundResponse({ description: 'Vote not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.voteService.remove(id);
  }
}
