// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateVoteDto } from './dto/create-vote.dto.js';
import { VoteResponseDto } from './dto/vote-response.dto.js';
import { UpdateVoteDto } from './dto/update-vote.dto.js';

const relations = [] as const;

@Injectable()
export class VoteService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateVoteDto): Promise<VoteResponseDto> {
    return this.database.create('vote', data, relations);
  }

  findAll(): Promise<VoteResponseDto[]> {
    return this.database.findAll('vote', relations);
  }

  findOne(id: string): Promise<VoteResponseDto | null> {
    return this.database.findOne('vote', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('vote', id, query);
  }

  update(id: string, data: UpdateVoteDto): Promise<VoteResponseDto> {
    return this.database.update('vote', id, data, relations);
  }

  remove(id: string): Promise<VoteResponseDto> {
    return this.database.remove('vote', id, relations);
  }
}
