// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateVoteDto } from './dto/create-vote.dto.js';
import { VoteResponseDto } from './dto/vote-response.dto.js';
import { UpdateVoteDto } from './dto/update-vote.dto.js';

@Injectable()
export class VoteService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateVoteDto): Promise<VoteResponseDto> {
    return this.prisma.vote.create({
      data: data as unknown as Prisma.VoteCreateInput,
    }) as unknown as Promise<VoteResponseDto>;
  }

  findAll(): Promise<VoteResponseDto[]> {
    return this.prisma.vote.findMany() as unknown as Promise<VoteResponseDto[]>;
  }

  findOne(id: string): Promise<VoteResponseDto | null> {
    return this.prisma.vote.findUnique({
      where: { id },
    }) as unknown as Promise<VoteResponseDto | null>;
  }

  update(id: string, data: UpdateVoteDto): Promise<VoteResponseDto> {
    return this.prisma.vote.update({
      where: { id },
      data: data as unknown as Prisma.VoteUpdateInput,
    }) as unknown as Promise<VoteResponseDto>;
  }

  remove(id: string): Promise<VoteResponseDto> {
    return this.prisma.vote.delete({
      where: { id },
    }) as unknown as Promise<VoteResponseDto>;
  }
}
