// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { assertEntityType } from '../surreal/entity-type.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateActionDto } from './dto/create-action.dto.js';
import { ActionResponseDto } from './dto/action-response.dto.js';
import { UpdateActionDto } from './dto/update-action.dto.js';

const relations = [] as const;

@Injectable()
export class ActionService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateActionDto): Promise<ActionResponseDto> {
    assertEntityType(data, 'Action');
    return this.database.create('action', data, relations);
  }

  findAll(): Promise<ActionResponseDto[]> {
    return this.database.findAll('action', relations);
  }

  findOne(id: string): Promise<ActionResponseDto | null> {
    return this.database.findOne('action', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('action', id, query);
  }

  update(id: string, data: UpdateActionDto): Promise<ActionResponseDto> {
    assertEntityType(data, 'Action', true);
    return this.database.update('action', id, data, relations);
  }

  remove(id: string): Promise<ActionResponseDto> {
    return this.database.remove('action', id, relations);
  }
}
