// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateActionDto } from './dto/create-action.dto.js';
import { ActionResponseDto } from './dto/action-response.dto.js';
import { UpdateActionDto } from './dto/update-action.dto.js';

@Injectable()
export class ActionService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateActionDto): Promise<ActionResponseDto> {
    return this.prisma.action.create({
      data: data as unknown as Prisma.ActionCreateInput,
    }) as unknown as Promise<ActionResponseDto>;
  }

  findAll(): Promise<ActionResponseDto[]> {
    return this.prisma.action.findMany() as unknown as Promise<
      ActionResponseDto[]
    >;
  }

  findOne(id: string): Promise<ActionResponseDto | null> {
    return this.prisma.action.findUnique({
      where: { id },
    }) as unknown as Promise<ActionResponseDto | null>;
  }

  update(id: string, data: UpdateActionDto): Promise<ActionResponseDto> {
    return this.prisma.action.update({
      where: { id },
      data: data as unknown as Prisma.ActionUpdateInput,
    }) as unknown as Promise<ActionResponseDto>;
  }

  remove(id: string): Promise<ActionResponseDto> {
    return this.prisma.action.delete({
      where: { id },
    }) as unknown as Promise<ActionResponseDto>;
  }
}
