// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { ActionController } from './action.controller.js';
import { ActionService } from './action.service.js';

@Module({
  controllers: [ActionController],
  providers: [ActionService],
})
export class ActionModule {}
