// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { ObservationController } from './observation.controller.js';
import { ObservationService } from './observation.service.js';

@Module({
  controllers: [ObservationController],
  providers: [ObservationService],
})
export class ObservationModule {}
