// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateObservationDto } from './dto/create-observation.dto.js';
import { ObservationResponseDto } from './dto/observation-response.dto.js';
import { UpdateObservationDto } from './dto/update-observation.dto.js';

const observationRelations = {
  observer: true,
} as const;

// API relations are expanded entities; Prisma requires nested relation operations.
function toObservationCreateInput(
  data: CreateObservationDto,
): Prisma.ObservationCreateInput {
  const prismaData: Record<string, unknown> = { ...data };
  if (data.observer !== undefined) {
    delete prismaData.observerRelationId;
    prismaData.observer = { connect: { id: data.observer.id } };
  }
  return prismaData as unknown as Prisma.ObservationCreateInput;
}

function toObservationUpdateInput(
  data: UpdateObservationDto,
): Prisma.ObservationUpdateInput {
  const prismaData: Record<string, unknown> = { ...data };
  if (data.observer !== undefined) {
    delete prismaData.observerRelationId;
    prismaData.observer = { connect: { id: data.observer.id } };
  }
  return prismaData as unknown as Prisma.ObservationUpdateInput;
}

@Injectable()
export class ObservationService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateObservationDto): Promise<ObservationResponseDto> {
    return this.prisma.observation.create({
      data: toObservationCreateInput(data),
      include: observationRelations,
    }) as unknown as Promise<ObservationResponseDto>;
  }

  findAll(): Promise<ObservationResponseDto[]> {
    return this.prisma.observation.findMany({
      include: observationRelations,
    }) as unknown as Promise<ObservationResponseDto[]>;
  }

  findOne(id: string): Promise<ObservationResponseDto | null> {
    return this.prisma.observation.findUnique({
      where: { id },
      include: observationRelations,
    }) as unknown as Promise<ObservationResponseDto | null>;
  }

  update(
    id: string,
    data: UpdateObservationDto,
  ): Promise<ObservationResponseDto> {
    return this.prisma.observation.update({
      where: { id },
      data: toObservationUpdateInput(data),
      include: observationRelations,
    }) as unknown as Promise<ObservationResponseDto>;
  }

  remove(id: string): Promise<ObservationResponseDto> {
    return this.prisma.observation.delete({
      where: { id },
      include: observationRelations,
    }) as unknown as Promise<ObservationResponseDto>;
  }
}
