// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { assertEntityType } from '../surreal/entity-type.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateObservationDto } from './dto/create-observation.dto.js';
import { ObservationResponseDto } from './dto/observation-response.dto.js';
import { UpdateObservationDto } from './dto/update-observation.dto.js';

const relations = [
  {
    property: 'observer',
    table: 'member',
    isArray: false,
    readOnly: false,
  },
] as const;

@Injectable()
export class ObservationService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateObservationDto): Promise<ObservationResponseDto> {
    assertEntityType(data, 'Observation');
    return this.database.create('observation', data, relations);
  }

  findAll(): Promise<ObservationResponseDto[]> {
    return this.database.findAll('observation', relations);
  }

  findOne(id: string): Promise<ObservationResponseDto | null> {
    return this.database.findOne('observation', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('observation', id, query);
  }

  update(
    id: string,
    data: UpdateObservationDto,
  ): Promise<ObservationResponseDto> {
    assertEntityType(data, 'Observation', true);
    return this.database.update('observation', id, data, relations);
  }

  remove(id: string): Promise<ObservationResponseDto> {
    return this.database.remove('observation', id, relations);
  }
}
