// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { CreateObservationDto } from './dto/create-observation.dto.js';
import { ObservationResponseDto } from './dto/observation-response.dto.js';
import { UpdateObservationDto } from './dto/update-observation.dto.js';

const relations = [
  {
    property: 'observer',
    table: 'member',
    isArray: false,
    readOnly: false,
  },
] as const;

@Injectable()
export class ObservationService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateObservationDto): Promise<ObservationResponseDto> {
    return this.database.create('observation', data, relations);
  }

  findAll(): Promise<ObservationResponseDto[]> {
    return this.database.findAll('observation', relations);
  }

  findOne(id: string): Promise<ObservationResponseDto | null> {
    return this.database.findOne('observation', id, relations);
  }

  update(
    id: string,
    data: UpdateObservationDto,
  ): Promise<ObservationResponseDto> {
    return this.database.update('observation', id, data, relations);
  }

  remove(id: string): Promise<ObservationResponseDto> {
    return this.database.remove('observation', id, relations);
  }
}
