// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBody,
  ApiBadRequestResponse,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateObservationDto } from './dto/create-observation.dto.js';
import { ObservationResponseDto } from './dto/observation-response.dto.js';
import { UpdateObservationDto } from './dto/update-observation.dto.js';
import { ObservationService } from './observation.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';

@ApiTags('observations')
@Controller('observations')
export class ObservationController {
  constructor(private readonly observationService: ObservationService) {}

  @Post()
  @ApiOperation({
    operationId: 'createObservation',
    summary: 'Create a Observation.',
  })
  @ApiBody({ type: CreateObservationDto })
  @ApiCreatedResponse({ type: ObservationResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType must match the entity schema title.',
  })
  create(@Body() data: CreateObservationDto): Promise<ObservationResponseDto> {
    return this.observationService.create(data);
  }

  @Get()
  @ApiOperation({
    operationId: 'listObservations',
    summary: 'List Observation records.',
  })
  @ApiOkResponse({ type: ObservationResponseDto, isArray: true })
  findAll(): Promise<ObservationResponseDto[]> {
    return this.observationService.findAll();
  }

  @Get(':id')
  @ApiOperation({
    operationId: 'getObservation',
    summary: 'Get a Observation by ID.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Observation ID.' })
  @ApiOkResponse({ type: ObservationResponseDto })
  @ApiNotFoundResponse({ description: 'Observation not found.' })
  async findOne(@Param('id') id: string): Promise<ObservationResponseDto> {
    const result = await this.observationService.findOne(id);
    if (!result) throw new NotFoundException('Observation not found.');
    return result;
  }

  @Get(':id/relations')
  @ApiOperation({
    operationId: 'listObservationRelations',
    summary: 'Query relationships associated with a Observation.',
  })
  @ApiParam({
    name: 'id',
    type: String,
    description: 'Observation ID (URL-encode slashes).',
  })
  @ApiOkResponse({ type: RelationshipResponseDto, isArray: true })
  @ApiBadRequestResponse({
    description: 'Invalid direction or equality filters.',
  })
  @ApiNotFoundResponse({ description: 'Observation not found.' })
  findRelations(
    @Param('id') id: string,
    @Query() query: RelationsQueryDto,
  ): Promise<RelationshipResponseDto[]> {
    return this.observationService.findRelations(id, query);
  }

  @Patch(':id')
  @ApiOperation({
    operationId: 'updateObservation',
    summary: 'Update a Observation.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Observation ID.' })
  @ApiBody({ type: UpdateObservationDto })
  @ApiOkResponse({ type: ObservationResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType cannot change from the entity schema title.',
  })
  @ApiNotFoundResponse({ description: 'Observation not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateObservationDto,
  ): Promise<ObservationResponseDto> {
    return this.observationService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    operationId: 'deleteObservation',
    summary: 'Delete a Observation.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Observation ID.' })
  @ApiNoContentResponse({ description: 'Observation deleted.' })
  @ApiNotFoundResponse({ description: 'Observation not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.observationService.remove(id);
  }
}
