// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateRoleDto } from './dto/create-role.dto.js';
import { RoleResponseDto } from './dto/role-response.dto.js';
import { UpdateRoleDto } from './dto/update-role.dto.js';

const roleRelations = {
  permissions: true,
  scope: true,
} as const;

@Injectable()
export class RoleService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateRoleDto): Promise<RoleResponseDto> {
    return this.prisma.role.create({
      data: data as unknown as Prisma.RoleCreateInput,
      include: roleRelations,
    }) as unknown as Promise<RoleResponseDto>;
  }

  findAll(): Promise<RoleResponseDto[]> {
    return this.prisma.role.findMany({
      include: roleRelations,
    }) as unknown as Promise<RoleResponseDto[]>;
  }

  findOne(id: string): Promise<RoleResponseDto | null> {
    return this.prisma.role.findUnique({
      where: { id },
      include: roleRelations,
    }) as unknown as Promise<RoleResponseDto | null>;
  }

  update(id: string, data: UpdateRoleDto): Promise<RoleResponseDto> {
    return this.prisma.role.update({
      where: { id },
      data: data as unknown as Prisma.RoleUpdateInput,
      include: roleRelations,
    }) as unknown as Promise<RoleResponseDto>;
  }

  remove(id: string): Promise<RoleResponseDto> {
    return this.prisma.role.delete({
      where: { id },
      include: roleRelations,
    }) as unknown as Promise<RoleResponseDto>;
  }
}
