// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateRoleDto } from './dto/create-role.dto.js';
import { RoleResponseDto } from './dto/role-response.dto.js';
import { UpdateRoleDto } from './dto/update-role.dto.js';

const relations = [
  {
    property: 'permissions',
    table: 'permission',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'scope',
    table: 'scope',
    isArray: false,
    readOnly: false,
  },
] as const;

@Injectable()
export class RoleService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateRoleDto): Promise<RoleResponseDto> {
    return this.database.create('role', data, relations);
  }

  findAll(): Promise<RoleResponseDto[]> {
    return this.database.findAll('role', relations);
  }

  findOne(id: string): Promise<RoleResponseDto | null> {
    return this.database.findOne('role', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('role', id, query);
  }

  update(id: string, data: UpdateRoleDto): Promise<RoleResponseDto> {
    return this.database.update('role', id, data, relations);
  }

  remove(id: string): Promise<RoleResponseDto> {
    return this.database.remove('role', id, relations);
  }
}
