// GENERATED by scripts/generate-personalities.ts. Do not edit by hand.
import { Personality } from "../game/personality.js";

export const personalities: Personality[] = [
  new Personality({
    "id": "FE_P040",
    "valence": "positive",
    "title": "A complaint received a fair hearing",
    "domain": "institutional_trust",
    "life_stages": [
      "adolescence",
      "adulthood"
    ],
    "exposure_pattern": "single_event",
    "experience": "An independent reviewer listened to the person's complaint, checked relevant evidence, and explained a fair decision.",
    "possible_meanings": [
      "Procedures can protect people with less power.",
      "Being heard can matter even when the outcome is not exactly what I requested."
    ],
    "reminder_cues": [
      "A clear appeal process",
      "An official gives reasons that can be checked"
    ],
    "possible_initial_responses": [
      "May prepare evidence and use the process.",
      "May wait for review rather than assume retaliation."
    ],
    "possible_decision_tendencies": [
      "May support independent review and due process.",
      "May accept an unfavorable outcome more readily when the reasoning is credible."
    ],
    "moderating_factors": [
      "Independence and accessibility of the current process",
      "Whether earlier findings were actually enforced"
    ],
    "alternative_outcome": "They may challenge an unfair procedure despite having had a good experience with another institution.",
    "source_ids": [
      "S10",
      "S11",
      "S15"
    ],
    "name": "emotional-regulation",
    "level": "high",
    "effect": "Can pause, name strong feelings, and choose a response instead of immediately acting on anger or fear.",
    "viewOfPeople": "People are often lonely beneath their social roles and need to feel seen before they can cooperate deeply.",
    "viewOfSelf": "A sensitive person who needs authenticity and emotional connection more than status.",
    "viewOfLife": "Life is about honest connection, self-expression, and refusing to live by empty appearances.",
    "beliefAboutGodAndAfterlife": "Is uncertain about God and afterlife, but experiences awe, love, and conscience as spiritually significant."
  }),
  new Personality({
    "id": "FE_N029",
    "valence": "negative",
    "title": "Serious road accident",
    "domain": "health_and_physical_safety",
    "life_stages": [
      "childhood",
      "adolescence",
      "adulthood"
    ],
    "exposure_pattern": "single_event",
    "experience": "The person survived a road accident involving serious injury or a credible threat to life.",
    "possible_meanings": [
      "Routine travel can become dangerous.",
      "I want some control over how I travel."
    ],
    "reminder_cues": [
      "Sudden braking",
      "A route or vehicle resembling the accident"
    ],
    "possible_initial_responses": [
      "May tense up, become quiet, or ask to stop.",
      "May prefer a trusted driver or another route."
    ],
    "possible_decision_tendencies": [
      "May weigh travel safety heavily in accepting an opportunity.",
      "May support realistic safety procedures even when inconvenient."
    ],
    "moderating_factors": [
      "Recovery from injury",
      "Current driving conditions and later travel experiences"
    ],
    "alternative_outcome": "They may return to ordinary travel while retaining specific preferences about speed and safety.",
    "source_ids": [
      "S04"
    ],
    "name": "initiative",
    "level": "medium",
    "effect": "Will often begin useful work or raise a problem without waiting for someone else to take charge.",
    "viewOfPeople": "People are often shaped by circumstance more than they admit, so judgment should be tempered by curiosity about context.",
    "viewOfSelf": "A product of both choice and circumstance who can still take responsibility for the next step.",
    "viewOfLife": "Life is about widening options for oneself and others rather than pretending everyone begins from the same place.",
    "beliefAboutGodAndAfterlife": "Leans toward secularism and is unsure whether any conscious existence continues after death."
  }),
  new Personality({
    "id": "FE_N039",
    "valence": "negative",
    "title": "Financial deception by someone trusted",
    "domain": "trust_and_belonging",
    "life_stages": [
      "adolescence",
      "adulthood"
    ],
    "exposure_pattern": "single_event",
    "experience": "A trusted person misrepresented a financial arrangement and caused a meaningful loss.",
    "possible_meanings": [
      "Personal warmth does not guarantee honesty.",
      "I should verify terms independently."
    ],
    "reminder_cues": [
      "Pressure to invest quickly",
      "A request to rely on friendship instead of written terms"
    ],
    "possible_initial_responses": [
      "May become suspicious of urgency.",
      "May seek records and outside advice."
    ],
    "possible_decision_tendencies": [
      "May favor transparent accounts and independent checks.",
      "May decline informal pooling of money."
    ],
    "moderating_factors": [
      "Size and recoverability of the loss",
      "Whether later transactions have been trustworthy"
    ],
    "alternative_outcome": "Careful verification may replace generalized suspicion as the person's main response.",
    "source_ids": [
      "S11",
      "S12"
    ],
    "name": "jealousy",
    "level": "medium",
    "effect": "Feels threatened by a close person's attention, affection, or loyalty toward someone else.",
    "viewOfPeople": "People deserve compassion because anyone can be harmed by bad luck, illness, loss, or social neglect.",
    "viewOfSelf": "A temporary beneficiary of conditions that could easily have been otherwise.",
    "viewOfLife": "Life is fragile, so a decent society protects dignity and reduces avoidable hardship.",
    "beliefAboutGodAndAfterlife": "Does not know whether God or an afterlife exists; moral concern comes from the reality of shared vulnerability."
  }),
  new Personality({
    "id": "FE_P016",
    "valence": "positive",
    "title": "Belonged to a cooperative team",
    "domain": "peer_and_school",
    "life_stages": [
      "childhood",
      "adolescence",
      "adulthood"
    ],
    "exposure_pattern": "extended_period",
    "experience": "In a team activity, roles were complementary and members practiced, contributed, and celebrated shared results.",
    "possible_meanings": [
      "Different strengths can produce a better result together.",
      "My contribution matters even when it is not the most visible."
    ],
    "reminder_cues": [
      "A problem requires several kinds of skill",
      "A teammate offers to share responsibility"
    ],
    "possible_initial_responses": [
      "May ask who is best placed to do each task.",
      "May coordinate rather than compete for every role."
    ],
    "possible_decision_tendencies": [
      "May favor balanced teams over a single dominant performer.",
      "May accept a supporting role when it serves the shared goal."
    ],
    "moderating_factors": [
      "Fairness of credit and workload",
      "Whether current team members are dependable"
    ],
    "alternative_outcome": "They may still prefer independent work for tasks where coordination offers little benefit.",
    "source_ids": [
      "S05",
      "S07"
    ],
    "name": "loyalty",
    "level": "high",
    "effect": "Stays committed to trusted people and groups, especially when they are facing difficulty.",
    "viewOfPeople": "People are bound to one another by responsibility, memory, and a shared moral law.",
    "viewOfSelf": "A link in a long chain of family and community, entrusted with preserving what is good.",
    "viewOfLife": "Life is a covenantal task: build a just community, remember history, and pass wisdom forward.",
    "beliefAboutGodAndAfterlife": "Believes in one God who calls people to ethical responsibility; holds a reverent but non-detailed view of what comes after death."
  }),
  new Personality({
    "id": "FE_P040",
    "valence": "positive",
    "title": "A complaint received a fair hearing",
    "domain": "institutional_trust",
    "life_stages": [
      "adolescence",
      "adulthood"
    ],
    "exposure_pattern": "single_event",
    "experience": "An independent reviewer listened to the person's complaint, checked relevant evidence, and explained a fair decision.",
    "possible_meanings": [
      "Procedures can protect people with less power.",
      "Being heard can matter even when the outcome is not exactly what I requested."
    ],
    "reminder_cues": [
      "A clear appeal process",
      "An official gives reasons that can be checked"
    ],
    "possible_initial_responses": [
      "May prepare evidence and use the process.",
      "May wait for review rather than assume retaliation."
    ],
    "possible_decision_tendencies": [
      "May support independent review and due process.",
      "May accept an unfavorable outcome more readily when the reasoning is credible."
    ],
    "moderating_factors": [
      "Independence and accessibility of the current process",
      "Whether earlier findings were actually enforced"
    ],
    "alternative_outcome": "They may challenge an unfair procedure despite having had a good experience with another institution.",
    "source_ids": [
      "S10",
      "S11",
      "S15"
    ],
    "name": "civic-mindedness",
    "level": "high",
    "effect": "Considers the health of the wider group and supports duties that benefit people beyond close friends.",
    "viewOfPeople": "People are drawn toward good but can confuse certainty with righteousness and power with virtue.",
    "viewOfSelf": "A morally accountable soul who should pair conviction with humility.",
    "viewOfLife": "Life is a struggle to purify motives, seek justice, and avoid becoming cruel in the name of a good cause.",
    "beliefAboutGodAndAfterlife": "Believes in God, divine justice, forgiveness, and an afterlife in which intentions as well as actions matter."
  }),
  new Personality({
    "id": "FE_N009",
    "valence": "negative",
    "title": "Repeated unfavorable comparison with a sibling",
    "domain": "family_and_caregiving",
    "life_stages": [
      "childhood",
      "adolescence"
    ],
    "exposure_pattern": "repeated",
    "experience": "Family members repeatedly praised a sibling while describing the child's contributions as inferior.",
    "possible_meanings": [
      "Recognition is scarce and someone else gets it.",
      "I have to distinguish myself to be noticed."
    ],
    "reminder_cues": [
      "Unequal public praise",
      "Two people are compared for one position"
    ],
    "possible_initial_responses": [
      "May feel overlooked even before the criteria are explained.",
      "May compete intensely or stop participating."
    ],
    "possible_decision_tendencies": [
      "May scrutinize how credit and opportunities are allocated.",
      "May reject a collaborative role if it seems invisible."
    ],
    "moderating_factors": [
      "Fairness of the current comparison",
      "Recognition received in other relationships"
    ],
    "alternative_outcome": "They may value fair recognition without viewing colleagues as rivals.",
    "source_ids": [
      "S03",
      "S13"
    ],
    "name": "laziness",
    "level": "medium",
    "effect": "Avoids effort when there is no immediate pressure and may leave necessary work for others.",
    "viewOfPeople": "People are animals with powerful instincts, but culture and reflection can help them channel those instincts wisely.",
    "viewOfSelf": "A biological being with the capacity to choose habits that improve life.",
    "viewOfLife": "Life is brief and embodied; health, friendship, curiosity, and reducing suffering make it worthwhile.",
    "beliefAboutGodAndAfterlife": "Does not believe in a supernatural afterlife and sees death as the end of individual experience."
  }),
  new Personality({
    "id": "FE_P047",
    "valence": "positive",
    "title": "A previously feared conversation went safely",
    "domain": "emotion_and_coping",
    "life_stages": [
      "adolescence",
      "adulthood"
    ],
    "exposure_pattern": "single_event",
    "experience": "The person prepared for a difficult conversation, expressed a reasonable need, and received a respectful response.",
    "possible_meanings": [
      "The outcome I fear is not inevitable.",
      "Preparation and respectful partners can make speaking up possible."
    ],
    "reminder_cues": [
      "A similar conversation with a safe person",
      "An opportunity to rehearse a request"
    ],
    "possible_initial_responses": [
      "May feel nervous but try a clear opening statement.",
      "May recall the earlier successful conversation."
    ],
    "possible_decision_tendencies": [
      "May voice a preference instead of automatically conceding.",
      "May choose a private discussion before a public confrontation."
    ],
    "moderating_factors": [
      "Similarity and safety of the new situation",
      "Whether the earlier success has been repeated"
    ],
    "alternative_outcome": "Confidence may grow gradually and remain specific to certain people or circumstances.",
    "source_ids": [
      "S09"
    ],
    "name": "irritability",
    "level": "medium",
    "effect": "Becomes annoyed quickly under inconvenience, fatigue, or criticism and may respond more sharply than intended.",
    "viewOfPeople": "People want recognition and will often compete for it, but they can mature beyond that competition.",
    "viewOfSelf": "A person trying to become capable, respected, and internally coherent.",
    "viewOfLife": "Life is self-creation through challenge, achievement, and responsibility for one's own standards.",
    "beliefAboutGodAndAfterlife": "Does not believe in a personal God or a guaranteed afterlife; sees this life as the arena for self-development."
  }),
  new Personality({
    "id": "FE_P020",
    "valence": "positive",
    "title": "Creative expression was taken seriously",
    "domain": "agency_and_mastery",
    "life_stages": [
      "childhood",
      "adolescence",
      "adulthood"
    ],
    "exposure_pattern": "repeated",
    "experience": "Other people listened to the person's stories, art, music, or ideas with interest and offered room to experiment.",
    "possible_meanings": [
      "My perspective can contribute something worthwhile.",
      "Exploration does not require immediate perfection."
    ],
    "reminder_cues": [
      "An open-ended problem",
      "An invitation to suggest an unconventional idea"
    ],
    "possible_initial_responses": [
      "May generate several possibilities.",
      "May share unfinished work for constructive discussion."
    ],
    "possible_decision_tendencies": [
      "May support limited experiments and creative participation.",
      "May value expressive activities alongside practical needs."
    ],
    "moderating_factors": [
      "Whether feedback respected ownership",
      "Resources and tolerance for uncertainty in the present setting"
    ],
    "alternative_outcome": "They may enjoy creative freedom while accepting constraints needed for a particular task.",
    "source_ids": [
      "S07",
      "S09"
    ],
    "name": "carefulness",
    "level": "high",
    "effect": "Checks important facts and avoids acting carelessly when a mistake could affect other people.",
    "viewOfPeople": "People cannot control everything, but they can control their judgment, conduct, and response.",
    "viewOfSelf": "A rational agent responsible for inner discipline rather than external outcomes.",
    "viewOfLife": "Life is practice in accepting what cannot be changed while acting virtuously where action is possible.",
    "beliefAboutGodAndAfterlife": "Is open to a providential order but treats virtue in this life as the central concern."
  }),
  new Personality({
    "id": "FE_P031",
    "valence": "positive",
    "title": "Shared finances were handled transparently",
    "domain": "trust_and_belonging",
    "life_stages": [
      "adolescence",
      "adulthood"
    ],
    "exposure_pattern": "extended_period",
    "experience": "In a household or group, contributions and expenses were explained openly and questions about money were welcomed.",
    "possible_meanings": [
      "Pooling resources can work when records are clear.",
      "Questions about money need not imply disloyalty."
    ],
    "reminder_cues": [
      "A shared budget with accessible records",
      "Someone requests clarification of an expense"
    ],
    "possible_initial_responses": [
      "May ask factual questions without assuming fraud.",
      "May share relevant information promptly."
    ],
    "possible_decision_tendencies": [
      "May support collective spending with transparent accounts.",
      "May prefer agreed rules to informal assurances."
    ],
    "moderating_factors": [
      "Quality of records and actual conduct",
      "Whether questioning remains free from retaliation"
    ],
    "alternative_outcome": "They may become cautious when transparency disappears rather than extending trust unconditionally.",
    "source_ids": [
      "S11"
    ],
    "name": "gullibility",
    "level": "low",
    "effect": "May accept confident claims or emotionally persuasive stories without enough verification.",
    "viewOfPeople": "People are bound to one another by responsibility, memory, and a shared moral law.",
    "viewOfSelf": "A link in a long chain of family and community, entrusted with preserving what is good.",
    "viewOfLife": "Life is a covenantal task: build a just community, remember history, and pass wisdom forward.",
    "beliefAboutGodAndAfterlife": "Believes in one God who calls people to ethical responsibility; holds a reverent but non-detailed view of what comes after death."
  }),
  new Personality({
    "id": "FE_P036",
    "valence": "positive",
    "title": "Care was explained and consent was respected",
    "domain": "health_and_physical_safety",
    "life_stages": [
      "childhood",
      "adolescence",
      "adulthood"
    ],
    "exposure_pattern": "repeated",
    "experience": "A clinician explained procedures, checked understanding, and offered meaningful choices whenever medically possible.",
    "possible_meanings": [
      "Expertise can work with my agency.",
      "Asking questions can improve care."
    ],
    "reminder_cues": [
      "A professional explains options clearly",
      "A decision requires understanding risks and benefits"
    ],
    "possible_initial_responses": [
      "May ask questions rather than silently endure uncertainty.",
      "May cooperate once they understand the plan."
    ],
    "possible_decision_tendencies": [
      "May seek expertise with transparent reasoning.",
      "May support informed consent in group services."
    ],
    "moderating_factors": [
      "Quality and honesty of the explanation",
      "Urgency and available alternatives"
    ],
    "alternative_outcome": "They may retain specific medical fears while being able to use trusted care effectively.",
    "source_ids": [
      "S02",
      "S09"
    ],
    "name": "gratitude",
    "level": "medium",
    "effect": "Notices help and good fortune, and tends to respond with appreciation rather than entitlement.",
    "viewOfPeople": "People are connected through duties, consequences, and the moral weight of their actions.",
    "viewOfSelf": "A soul with obligations shaped by family, role, and the consequences of prior choices.",
    "viewOfLife": "Life is a path of learning to act rightly, fulfill duty, and grow beyond selfish desire.",
    "beliefAboutGodAndAfterlife": "Believes in a divine order, karma, and continuing existence or rebirth after death."
  })
];
// 32124318
// 32121451