// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { assertEntityType } from '../surreal/entity-type.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateOrganizationDto } from './dto/create-organization.dto.js';
import { OrganizationResponseDto } from './dto/organization-response.dto.js';
import { UpdateOrganizationDto } from './dto/update-organization.dto.js';

const relations = [] as const;

@Injectable()
export class OrganizationService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateOrganizationDto): Promise<OrganizationResponseDto> {
    assertEntityType(data, 'Organization');
    return this.database.create('organization', data, relations);
  }

  findAll(): Promise<OrganizationResponseDto[]> {
    return this.database.findAll('organization', relations);
  }

  findOne(id: string): Promise<OrganizationResponseDto | null> {
    return this.database.findOne('organization', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('organization', id, query);
  }

  update(
    id: string,
    data: UpdateOrganizationDto,
  ): Promise<OrganizationResponseDto> {
    assertEntityType(data, 'Organization', true);
    return this.database.update('organization', id, data, relations);
  }

  remove(id: string): Promise<OrganizationResponseDto> {
    return this.database.remove('organization', id, relations);
  }
}
