// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
} from '@nestjs/common';
import {
  ApiBody,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateOrganizationDto } from './dto/create-organization.dto.js';
import { OrganizationResponseDto } from './dto/organization-response.dto.js';
import { UpdateOrganizationDto } from './dto/update-organization.dto.js';
import { OrganizationService } from './organization.service.js';

@ApiTags('organizations')
@Controller('organizations')
export class OrganizationController {
  constructor(private readonly organizationService: OrganizationService) {}

  @Post()
  @ApiOperation({
    operationId: 'createOrganization',
    summary: 'Create a Organization.',
  })
  @ApiBody({ type: CreateOrganizationDto })
  @ApiCreatedResponse({ type: OrganizationResponseDto })
  create(
    @Body() data: CreateOrganizationDto,
  ): Promise<OrganizationResponseDto> {
    return this.organizationService.create(data);
  }

  @Get()
  @ApiOperation({
    operationId: 'listOrganizations',
    summary: 'List Organization records.',
  })
  @ApiOkResponse({ type: OrganizationResponseDto, isArray: true })
  findAll(): Promise<OrganizationResponseDto[]> {
    return this.organizationService.findAll();
  }

  @Get(':id')
  @ApiOperation({
    operationId: 'getOrganization',
    summary: 'Get a Organization by ID.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Organization ID.' })
  @ApiOkResponse({ type: OrganizationResponseDto })
  @ApiNotFoundResponse({ description: 'Organization not found.' })
  async findOne(@Param('id') id: string): Promise<OrganizationResponseDto> {
    const result = await this.organizationService.findOne(id);
    if (!result) throw new NotFoundException('Organization not found.');
    return result;
  }

  @Patch(':id')
  @ApiOperation({
    operationId: 'updateOrganization',
    summary: 'Update a Organization.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Organization ID.' })
  @ApiBody({ type: UpdateOrganizationDto })
  @ApiOkResponse({ type: OrganizationResponseDto })
  @ApiNotFoundResponse({ description: 'Organization not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateOrganizationDto,
  ): Promise<OrganizationResponseDto> {
    return this.organizationService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    operationId: 'deleteOrganization',
    summary: 'Delete a Organization.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Organization ID.' })
  @ApiNoContentResponse({ description: 'Organization deleted.' })
  @ApiNotFoundResponse({ description: 'Organization not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.organizationService.remove(id);
  }
}
