// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateOrganizationDto } from './dto/create-organization.dto.js';
import { OrganizationResponseDto } from './dto/organization-response.dto.js';
import { UpdateOrganizationDto } from './dto/update-organization.dto.js';

@Injectable()
export class OrganizationService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateOrganizationDto): Promise<OrganizationResponseDto> {
    return this.prisma.organization.create({
      data: data as unknown as Prisma.OrganizationCreateInput,
    }) as unknown as Promise<OrganizationResponseDto>;
  }

  findAll(): Promise<OrganizationResponseDto[]> {
    return this.prisma.organization.findMany() as unknown as Promise<
      OrganizationResponseDto[]
    >;
  }

  findOne(id: string): Promise<OrganizationResponseDto | null> {
    return this.prisma.organization.findUnique({
      where: { id },
    }) as unknown as Promise<OrganizationResponseDto | null>;
  }

  update(
    id: string,
    data: UpdateOrganizationDto,
  ): Promise<OrganizationResponseDto> {
    return this.prisma.organization.update({
      where: { id },
      data: data as unknown as Prisma.OrganizationUpdateInput,
    }) as unknown as Promise<OrganizationResponseDto>;
  }

  remove(id: string): Promise<OrganizationResponseDto> {
    return this.prisma.organization.delete({
      where: { id },
    }) as unknown as Promise<OrganizationResponseDto>;
  }
}
