import type { CreateMemberDto } from 'prototype-client';

const fakeMemberNames = [
  'Ali Rezaei',
  'Sara Ahmadi',
  'Mohammad Mohammadi',
  'Neda Karimi',
  'Amir Hosseini',
  'Leila Rahimi',
  'Reza Ebrahimi',
  'Shirin Moradi',
  'Arash Jafari',
  'Mina Ghasemi',
  'Farhad Kazemi',
  'Parisa Sadeghi',
  'Kian Rostami',
  'Nazanin Hashemi',
  'Mehdi Mahmoudi',
  'Yasaman Amini',
  'Pouya Akbari',
  'Mahsa Nouri',
  'Sina Bagheri',
  'Golnaz Azizi',
  'Babak Salehi',
  'Sepideh Mousavi',
  'Navid Heidari',
  'Taraneh Abbasi',
  'Omid Shariati',
  'Sahar Zand',
  'Dariush Farrokhzad',
  'Roya Khosravi',
  'Kaveh Pahlavan',
  'Arezoo Vaziri',
  'Shahram Nikpour',
  'Maryam Tavakoli',
  'Behnam Ranjbar',
  'Pegah Daryaei',
  'Soroush Kamali',
  'Elaheh Ansari',
  'Maziar Fallahi',
  'Samira Alavi',
  'Hooman Najafi',
  'Niloufar Bahrami',
  'Masoud Fathi',
  'Bahar Jamshidi',
  'Ashkan Yeganeh',
  'Mitra Kiani',
  'Iman Boroumand',
  'Aida Shahbazi',
  'Peyman Rastegar',
  'Donya Mehrabi',
  'Siavash Khatami',
  'Ghazal Pourmand',
  'Ramin Dehghan',
  'Setareh Khademi',
  'Nima Soltani',
  'Kimia Omrani',
  'Javad Maleki',
  'Anahita Esfandiari',
  'Ehsan Motamedi',
  'Elham Kargar',
  'Kamran Samadi',
  'Nasim Afshari',
  'Farshad Mirzaei',
  'Shabnam Dadgar',
  'Milad Panahi',
  'Sanaz Ghorbani',
  'Keyvan Daneshvar',
  'Farnaz Safavi',
  'Alireza Roudaki',
  'Zahra Norouzi',
  'Kourosh Sepahvand',
  'Mahtab Parsa',
  'Vahid Aghaei',
  'Hasti Moini',
  'Shayan Firoozi',
  'Mona Khorrami',
  'Mehrdad Adibi',
  'Yalda Nezamzadeh',
  'Pashang Arjomand',
  'Ladan Rakhshani',
  'Bijan Kermani',
  'Marjan Shafiei',
  'Afshin Khodadadi',
  'Nooshin Sarmadi',
  'Arman Talebi',
  'Shiva Goudarzi',
  'Payam Erfani',
  'Tannaz Keshavarz',
  'Hormoz Shokri',
  'Negin Zarei',
  'Pedram Ghafari',
  'Forough Ardestani',
  'Mani Dolatshahi',
  'Mandana Vakili',
  'Kambiz Arefi',
  'Solmaz Faramarzi',
  'Roozbeh Naderi',
  'Azadeh Pournazari',
  'Jamshid Sarraf',
  'Katayoun Moeini',
  'Kasra Hedayati',
  'Pantea Shams',
];

export const fakeMembers: CreateMemberDto[] = fakeMemberNames.map((name, index) => {
  const sequence = String(index + 1).padStart(12, '0');
  const timestamp = new Date(Date.UTC(2025, 0, index + 1, 9)).toISOString();

  return {
    id: (index + 1).toString(),
    ifsId: `Member/${index + 1}`,
    entityType: 'Member',
    entityDocumentationUrl: 'https://individualfreedom.systems/entities/member',
    name,
    permissions: [],
    isOwner: index === 0,
    createdAt: timestamp,
    updatedAt: timestamp,
  };
});
