// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateGroupDto } from './dto/create-group.dto.js';
import { GroupResponseDto } from './dto/group-response.dto.js';
import { UpdateGroupDto } from './dto/update-group.dto.js';

@Injectable()
export class GroupService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateGroupDto): Promise<GroupResponseDto> {
    return this.prisma.group.create({
      data: data as unknown as Prisma.GroupCreateInput,
    }) as unknown as Promise<GroupResponseDto>;
  }

  findAll(): Promise<GroupResponseDto[]> {
    return this.prisma.group.findMany() as unknown as Promise<
      GroupResponseDto[]
    >;
  }

  findOne(id: string): Promise<GroupResponseDto | null> {
    return this.prisma.group.findUnique({
      where: { id },
    }) as unknown as Promise<GroupResponseDto | null>;
  }

  update(id: string, data: UpdateGroupDto): Promise<GroupResponseDto> {
    return this.prisma.group.update({
      where: { id },
      data: data as unknown as Prisma.GroupUpdateInput,
    }) as unknown as Promise<GroupResponseDto>;
  }

  remove(id: string): Promise<GroupResponseDto> {
    return this.prisma.group.delete({
      where: { id },
    }) as unknown as Promise<GroupResponseDto>;
  }
}
