// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateGroupDto } from './dto/create-group.dto.js';
import { GroupResponseDto } from './dto/group-response.dto.js';
import { UpdateGroupDto } from './dto/update-group.dto.js';

const relations = [
  {
    property: 'groups',
    table: 'group',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'members',
    table: 'member',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'organizations',
    table: 'organization',
    isArray: true,
    readOnly: false,
  },
] as const;

@Injectable()
export class GroupService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateGroupDto): Promise<GroupResponseDto> {
    return this.database.create('group', data, relations);
  }

  findAll(): Promise<GroupResponseDto[]> {
    return this.database.findAll('group', relations);
  }

  findOne(id: string): Promise<GroupResponseDto | null> {
    return this.database.findOne('group', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('group', id, query);
  }

  update(id: string, data: UpdateGroupDto): Promise<GroupResponseDto> {
    return this.database.update('group', id, data, relations);
  }

  remove(id: string): Promise<GroupResponseDto> {
    return this.database.remove('group', id, relations);
  }
}
