// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBody,
  ApiBadRequestResponse,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateGroupDto } from './dto/create-group.dto.js';
import { GroupResponseDto } from './dto/group-response.dto.js';
import { UpdateGroupDto } from './dto/update-group.dto.js';
import { GroupService } from './group.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';

@ApiTags('groups')
@Controller('groups')
export class GroupController {
  constructor(private readonly groupService: GroupService) {}

  @Post()
  @ApiOperation({ operationId: 'createGroup', summary: 'Create a Group.' })
  @ApiBody({ type: CreateGroupDto })
  @ApiCreatedResponse({ type: GroupResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType must match the entity schema title.',
  })
  create(@Body() data: CreateGroupDto): Promise<GroupResponseDto> {
    return this.groupService.create(data);
  }

  @Get()
  @ApiOperation({ operationId: 'listGroups', summary: 'List Group records.' })
  @ApiOkResponse({ type: GroupResponseDto, isArray: true })
  findAll(): Promise<GroupResponseDto[]> {
    return this.groupService.findAll();
  }

  @Get(':id')
  @ApiOperation({ operationId: 'getGroup', summary: 'Get a Group by ID.' })
  @ApiParam({ name: 'id', type: String, description: 'Group ID.' })
  @ApiOkResponse({ type: GroupResponseDto })
  @ApiNotFoundResponse({ description: 'Group not found.' })
  async findOne(@Param('id') id: string): Promise<GroupResponseDto> {
    const result = await this.groupService.findOne(id);
    if (!result) throw new NotFoundException('Group not found.');
    return result;
  }

  @Get(':id/relations')
  @ApiOperation({
    operationId: 'listGroupRelations',
    summary: 'Query relationships associated with a Group.',
  })
  @ApiParam({
    name: 'id',
    type: String,
    description: 'Group ID (URL-encode slashes).',
  })
  @ApiOkResponse({ type: RelationshipResponseDto, isArray: true })
  @ApiBadRequestResponse({
    description: 'Invalid direction or equality filters.',
  })
  @ApiNotFoundResponse({ description: 'Group not found.' })
  findRelations(
    @Param('id') id: string,
    @Query() query: RelationsQueryDto,
  ): Promise<RelationshipResponseDto[]> {
    return this.groupService.findRelations(id, query);
  }

  @Patch(':id')
  @ApiOperation({ operationId: 'updateGroup', summary: 'Update a Group.' })
  @ApiParam({ name: 'id', type: String, description: 'Group ID.' })
  @ApiBody({ type: UpdateGroupDto })
  @ApiOkResponse({ type: GroupResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType cannot change from the entity schema title.',
  })
  @ApiNotFoundResponse({ description: 'Group not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateGroupDto,
  ): Promise<GroupResponseDto> {
    return this.groupService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ operationId: 'deleteGroup', summary: 'Delete a Group.' })
  @ApiParam({ name: 'id', type: String, description: 'Group ID.' })
  @ApiNoContentResponse({ description: 'Group deleted.' })
  @ApiNotFoundResponse({ description: 'Group not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.groupService.remove(id);
  }
}
