// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
} from '@nestjs/common';
import {
  ApiBody,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateScopeDto } from './dto/create-scope.dto.js';
import { ScopeResponseDto } from './dto/scope-response.dto.js';
import { UpdateScopeDto } from './dto/update-scope.dto.js';
import { ScopeService } from './scope.service.js';

@ApiTags('scopes')
@Controller('scopes')
export class ScopeController {
  constructor(private readonly scopeService: ScopeService) {}

  @Post()
  @ApiOperation({ operationId: 'createScope', summary: 'Create a Scope.' })
  @ApiBody({ type: CreateScopeDto })
  @ApiCreatedResponse({ type: ScopeResponseDto })
  create(@Body() data: CreateScopeDto): Promise<ScopeResponseDto> {
    return this.scopeService.create(data);
  }

  @Get()
  @ApiOperation({ operationId: 'listScopes', summary: 'List Scope records.' })
  @ApiOkResponse({ type: ScopeResponseDto, isArray: true })
  findAll(): Promise<ScopeResponseDto[]> {
    return this.scopeService.findAll();
  }

  @Get(':id')
  @ApiOperation({ operationId: 'getScope', summary: 'Get a Scope by ID.' })
  @ApiParam({ name: 'id', type: String, description: 'Scope ID.' })
  @ApiOkResponse({ type: ScopeResponseDto })
  @ApiNotFoundResponse({ description: 'Scope not found.' })
  async findOne(@Param('id') id: string): Promise<ScopeResponseDto> {
    const result = await this.scopeService.findOne(id);
    if (!result) throw new NotFoundException('Scope not found.');
    return result;
  }

  @Patch(':id')
  @ApiOperation({ operationId: 'updateScope', summary: 'Update a Scope.' })
  @ApiParam({ name: 'id', type: String, description: 'Scope ID.' })
  @ApiBody({ type: UpdateScopeDto })
  @ApiOkResponse({ type: ScopeResponseDto })
  @ApiNotFoundResponse({ description: 'Scope not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateScopeDto,
  ): Promise<ScopeResponseDto> {
    return this.scopeService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ operationId: 'deleteScope', summary: 'Delete a Scope.' })
  @ApiParam({ name: 'id', type: String, description: 'Scope ID.' })
  @ApiNoContentResponse({ description: 'Scope deleted.' })
  @ApiNotFoundResponse({ description: 'Scope not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.scopeService.remove(id);
  }
}
