// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateScopeDto } from './dto/create-scope.dto.js';
import { ScopeResponseDto } from './dto/scope-response.dto.js';
import { UpdateScopeDto } from './dto/update-scope.dto.js';

@Injectable()
export class ScopeService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateScopeDto): Promise<ScopeResponseDto> {
    return this.prisma.scope.create({
      data: data as unknown as Prisma.ScopeCreateInput,
    }) as unknown as Promise<ScopeResponseDto>;
  }

  findAll(): Promise<ScopeResponseDto[]> {
    return this.prisma.scope.findMany() as unknown as Promise<
      ScopeResponseDto[]
    >;
  }

  findOne(id: string): Promise<ScopeResponseDto | null> {
    return this.prisma.scope.findUnique({
      where: { id },
    }) as unknown as Promise<ScopeResponseDto | null>;
  }

  update(id: string, data: UpdateScopeDto): Promise<ScopeResponseDto> {
    return this.prisma.scope.update({
      where: { id },
      data: data as unknown as Prisma.ScopeUpdateInput,
    }) as unknown as Promise<ScopeResponseDto>;
  }

  remove(id: string): Promise<ScopeResponseDto> {
    return this.prisma.scope.delete({
      where: { id },
    }) as unknown as Promise<ScopeResponseDto>;
  }
}
