// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateScopeDto } from './dto/create-scope.dto.js';
import { ScopeResponseDto } from './dto/scope-response.dto.js';
import { UpdateScopeDto } from './dto/update-scope.dto.js';

const relations = [] as const;

@Injectable()
export class ScopeService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateScopeDto): Promise<ScopeResponseDto> {
    return this.database.create('scope', data, relations);
  }

  findAll(): Promise<ScopeResponseDto[]> {
    return this.database.findAll('scope', relations);
  }

  findOne(id: string): Promise<ScopeResponseDto | null> {
    return this.database.findOne('scope', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('scope', id, query);
  }

  update(id: string, data: UpdateScopeDto): Promise<ScopeResponseDto> {
    return this.database.update('scope', id, data, relations);
  }

  remove(id: string): Promise<ScopeResponseDto> {
    return this.database.remove('scope', id, relations);
  }
}
