// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { ScopeController } from './scope.controller.js';
import { ScopeService } from './scope.service.js';

@Module({
  controllers: [ScopeController],
  providers: [ScopeService],
})
export class ScopeModule {}
