// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateRuleDto } from './dto/create-rule.dto.js';
import { RuleResponseDto } from './dto/rule-response.dto.js';
import { UpdateRuleDto } from './dto/update-rule.dto.js';

@Injectable()
export class RuleService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateRuleDto): Promise<RuleResponseDto> {
    return this.prisma.rule.create({
      data: data as unknown as Prisma.RuleCreateInput,
    }) as unknown as Promise<RuleResponseDto>;
  }

  findAll(): Promise<RuleResponseDto[]> {
    return this.prisma.rule.findMany() as unknown as Promise<RuleResponseDto[]>;
  }

  findOne(id: string): Promise<RuleResponseDto | null> {
    return this.prisma.rule.findUnique({
      where: { id },
    }) as unknown as Promise<RuleResponseDto | null>;
  }

  update(id: string, data: UpdateRuleDto): Promise<RuleResponseDto> {
    return this.prisma.rule.update({
      where: { id },
      data: data as unknown as Prisma.RuleUpdateInput,
    }) as unknown as Promise<RuleResponseDto>;
  }

  remove(id: string): Promise<RuleResponseDto> {
    return this.prisma.rule.delete({
      where: { id },
    }) as unknown as Promise<RuleResponseDto>;
  }
}
