// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { CreateRuleDto } from './dto/create-rule.dto.js';
import { RuleResponseDto } from './dto/rule-response.dto.js';
import { UpdateRuleDto } from './dto/update-rule.dto.js';

const relations = [] as const;

@Injectable()
export class RuleService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateRuleDto): Promise<RuleResponseDto> {
    return this.database.create('rule', data, relations);
  }

  findAll(): Promise<RuleResponseDto[]> {
    return this.database.findAll('rule', relations);
  }

  findOne(id: string): Promise<RuleResponseDto | null> {
    return this.database.findOne('rule', id, relations);
  }

  update(id: string, data: UpdateRuleDto): Promise<RuleResponseDto> {
    return this.database.update('rule', id, data, relations);
  }

  remove(id: string): Promise<RuleResponseDto> {
    return this.database.remove('rule', id, relations);
  }
}
