// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBody,
  ApiBadRequestResponse,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateRuleDto } from './dto/create-rule.dto.js';
import { RuleResponseDto } from './dto/rule-response.dto.js';
import { UpdateRuleDto } from './dto/update-rule.dto.js';
import { RuleService } from './rule.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';

@ApiTags('rules')
@Controller('rules')
export class RuleController {
  constructor(private readonly ruleService: RuleService) {}

  @Post()
  @ApiOperation({ operationId: 'createRule', summary: 'Create a Rule.' })
  @ApiBody({ type: CreateRuleDto })
  @ApiCreatedResponse({ type: RuleResponseDto })
  create(@Body() data: CreateRuleDto): Promise<RuleResponseDto> {
    return this.ruleService.create(data);
  }

  @Get()
  @ApiOperation({ operationId: 'listRules', summary: 'List Rule records.' })
  @ApiOkResponse({ type: RuleResponseDto, isArray: true })
  findAll(): Promise<RuleResponseDto[]> {
    return this.ruleService.findAll();
  }

  @Get(':id')
  @ApiOperation({ operationId: 'getRule', summary: 'Get a Rule by ID.' })
  @ApiParam({ name: 'id', type: String, description: 'Rule ID.' })
  @ApiOkResponse({ type: RuleResponseDto })
  @ApiNotFoundResponse({ description: 'Rule not found.' })
  async findOne(@Param('id') id: string): Promise<RuleResponseDto> {
    const result = await this.ruleService.findOne(id);
    if (!result) throw new NotFoundException('Rule not found.');
    return result;
  }

  @Get(':id/relations')
  @ApiOperation({
    operationId: 'listRuleRelations',
    summary: 'Query relationships associated with a Rule.',
  })
  @ApiParam({
    name: 'id',
    type: String,
    description: 'Rule ID (URL-encode slashes).',
  })
  @ApiOkResponse({ type: RelationshipResponseDto, isArray: true })
  @ApiBadRequestResponse({
    description: 'Invalid direction or equality filters.',
  })
  @ApiNotFoundResponse({ description: 'Rule not found.' })
  findRelations(
    @Param('id') id: string,
    @Query() query: RelationsQueryDto,
  ): Promise<RelationshipResponseDto[]> {
    return this.ruleService.findRelations(id, query);
  }

  @Patch(':id')
  @ApiOperation({ operationId: 'updateRule', summary: 'Update a Rule.' })
  @ApiParam({ name: 'id', type: String, description: 'Rule ID.' })
  @ApiBody({ type: UpdateRuleDto })
  @ApiOkResponse({ type: RuleResponseDto })
  @ApiNotFoundResponse({ description: 'Rule not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateRuleDto,
  ): Promise<RuleResponseDto> {
    return this.ruleService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ operationId: 'deleteRule', summary: 'Delete a Rule.' })
  @ApiParam({ name: 'id', type: String, description: 'Rule ID.' })
  @ApiNoContentResponse({ description: 'Rule deleted.' })
  @ApiNotFoundResponse({ description: 'Rule not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.ruleService.remove(id);
  }
}
