// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBody,
  ApiBadRequestResponse,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateReviewCommentDto } from './dto/create-review-comment.dto.js';
import { ReviewCommentResponseDto } from './dto/review-comment-response.dto.js';
import { UpdateReviewCommentDto } from './dto/update-review-comment.dto.js';
import { ReviewCommentService } from './review-comment.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';

@ApiTags('review-comments')
@Controller('review-comments')
export class ReviewCommentController {
  constructor(private readonly reviewCommentService: ReviewCommentService) {}

  @Post()
  @ApiOperation({
    operationId: 'createReviewComment',
    summary: 'Create a ReviewComment.',
  })
  @ApiBody({ type: CreateReviewCommentDto })
  @ApiCreatedResponse({ type: ReviewCommentResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType must match the entity schema title.',
  })
  create(
    @Body() data: CreateReviewCommentDto,
  ): Promise<ReviewCommentResponseDto> {
    return this.reviewCommentService.create(data);
  }

  @Get()
  @ApiOperation({
    operationId: 'listReviewComments',
    summary: 'List ReviewComment records.',
  })
  @ApiOkResponse({ type: ReviewCommentResponseDto, isArray: true })
  findAll(): Promise<ReviewCommentResponseDto[]> {
    return this.reviewCommentService.findAll();
  }

  @Get(':id')
  @ApiOperation({
    operationId: 'getReviewComment',
    summary: 'Get a ReviewComment by ID.',
  })
  @ApiParam({ name: 'id', type: String, description: 'ReviewComment ID.' })
  @ApiOkResponse({ type: ReviewCommentResponseDto })
  @ApiNotFoundResponse({ description: 'ReviewComment not found.' })
  async findOne(@Param('id') id: string): Promise<ReviewCommentResponseDto> {
    const result = await this.reviewCommentService.findOne(id);
    if (!result) throw new NotFoundException('ReviewComment not found.');
    return result;
  }

  @Get(':id/relations')
  @ApiOperation({
    operationId: 'listReviewCommentRelations',
    summary: 'Query relationships associated with a ReviewComment.',
  })
  @ApiParam({
    name: 'id',
    type: String,
    description: 'ReviewComment ID (URL-encode slashes).',
  })
  @ApiOkResponse({ type: RelationshipResponseDto, isArray: true })
  @ApiBadRequestResponse({
    description: 'Invalid direction or equality filters.',
  })
  @ApiNotFoundResponse({ description: 'ReviewComment not found.' })
  findRelations(
    @Param('id') id: string,
    @Query() query: RelationsQueryDto,
  ): Promise<RelationshipResponseDto[]> {
    return this.reviewCommentService.findRelations(id, query);
  }

  @Patch(':id')
  @ApiOperation({
    operationId: 'updateReviewComment',
    summary: 'Update a ReviewComment.',
  })
  @ApiParam({ name: 'id', type: String, description: 'ReviewComment ID.' })
  @ApiBody({ type: UpdateReviewCommentDto })
  @ApiOkResponse({ type: ReviewCommentResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType cannot change from the entity schema title.',
  })
  @ApiNotFoundResponse({ description: 'ReviewComment not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateReviewCommentDto,
  ): Promise<ReviewCommentResponseDto> {
    return this.reviewCommentService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    operationId: 'deleteReviewComment',
    summary: 'Delete a ReviewComment.',
  })
  @ApiParam({ name: 'id', type: String, description: 'ReviewComment ID.' })
  @ApiNoContentResponse({ description: 'ReviewComment deleted.' })
  @ApiNotFoundResponse({ description: 'ReviewComment not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.reviewCommentService.remove(id);
  }
}
