// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { CreateReviewCommentDto } from './dto/create-review-comment.dto.js';
import { ReviewCommentResponseDto } from './dto/review-comment-response.dto.js';
import { UpdateReviewCommentDto } from './dto/update-review-comment.dto.js';

const relations = [] as const;

@Injectable()
export class ReviewCommentService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateReviewCommentDto): Promise<ReviewCommentResponseDto> {
    return this.database.create('review_comment', data, relations);
  }

  findAll(): Promise<ReviewCommentResponseDto[]> {
    return this.database.findAll('review_comment', relations);
  }

  findOne(id: string): Promise<ReviewCommentResponseDto | null> {
    return this.database.findOne('review_comment', id, relations);
  }

  update(
    id: string,
    data: UpdateReviewCommentDto,
  ): Promise<ReviewCommentResponseDto> {
    return this.database.update('review_comment', id, data, relations);
  }

  remove(id: string): Promise<ReviewCommentResponseDto> {
    return this.database.remove('review_comment', id, relations);
  }
}
