// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateReviewCommentDto } from './dto/create-review-comment.dto.js';
import { ReviewCommentResponseDto } from './dto/review-comment-response.dto.js';
import { UpdateReviewCommentDto } from './dto/update-review-comment.dto.js';

@Injectable()
export class ReviewCommentService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateReviewCommentDto): Promise<ReviewCommentResponseDto> {
    return this.prisma.reviewComment.create({
      data: data as unknown as Prisma.ReviewCommentCreateInput,
    }) as unknown as Promise<ReviewCommentResponseDto>;
  }

  findAll(): Promise<ReviewCommentResponseDto[]> {
    return this.prisma.reviewComment.findMany() as unknown as Promise<
      ReviewCommentResponseDto[]
    >;
  }

  findOne(id: string): Promise<ReviewCommentResponseDto | null> {
    return this.prisma.reviewComment.findUnique({
      where: { id },
    }) as unknown as Promise<ReviewCommentResponseDto | null>;
  }

  update(
    id: string,
    data: UpdateReviewCommentDto,
  ): Promise<ReviewCommentResponseDto> {
    return this.prisma.reviewComment.update({
      where: { id },
      data: data as unknown as Prisma.ReviewCommentUpdateInput,
    }) as unknown as Promise<ReviewCommentResponseDto>;
  }

  remove(id: string): Promise<ReviewCommentResponseDto> {
    return this.prisma.reviewComment.delete({
      where: { id },
    }) as unknown as Promise<ReviewCommentResponseDto>;
  }
}
