// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { ReviewCommentController } from './review-comment.controller.js';
import { ReviewCommentService } from './review-comment.service.js';

@Module({
  controllers: [ReviewCommentController],
  providers: [ReviewCommentService],
})
export class ReviewCommentModule {}
