// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateLabelDto } from './dto/create-label.dto.js';
import { LabelResponseDto } from './dto/label-response.dto.js';
import { UpdateLabelDto } from './dto/update-label.dto.js';

@Injectable()
export class LabelService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateLabelDto): Promise<LabelResponseDto> {
    return this.prisma.label.create({
      data: data as unknown as Prisma.LabelCreateInput,
    }) as unknown as Promise<LabelResponseDto>;
  }

  findAll(): Promise<LabelResponseDto[]> {
    return this.prisma.label.findMany() as unknown as Promise<
      LabelResponseDto[]
    >;
  }

  findOne(id: string): Promise<LabelResponseDto | null> {
    return this.prisma.label.findUnique({
      where: { id },
    }) as unknown as Promise<LabelResponseDto | null>;
  }

  update(id: string, data: UpdateLabelDto): Promise<LabelResponseDto> {
    return this.prisma.label.update({
      where: { id },
      data: data as unknown as Prisma.LabelUpdateInput,
    }) as unknown as Promise<LabelResponseDto>;
  }

  remove(id: string): Promise<LabelResponseDto> {
    return this.prisma.label.delete({
      where: { id },
    }) as unknown as Promise<LabelResponseDto>;
  }
}
