// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { LabelController } from './label.controller.js';
import { LabelService } from './label.service.js';

@Module({
  controllers: [LabelController],
  providers: [LabelService],
})
export class LabelModule {}
