// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateLabelDto } from './dto/create-label.dto.js';
import { LabelResponseDto } from './dto/label-response.dto.js';
import { UpdateLabelDto } from './dto/update-label.dto.js';

const relations = [] as const;

@Injectable()
export class LabelService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateLabelDto): Promise<LabelResponseDto> {
    return this.database.create('label', data, relations);
  }

  findAll(): Promise<LabelResponseDto[]> {
    return this.database.findAll('label', relations);
  }

  findOne(id: string): Promise<LabelResponseDto | null> {
    return this.database.findOne('label', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('label', id, query);
  }

  update(id: string, data: UpdateLabelDto): Promise<LabelResponseDto> {
    return this.database.update('label', id, data, relations);
  }

  remove(id: string): Promise<LabelResponseDto> {
    return this.database.remove('label', id, relations);
  }
}
