// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateCommentDto } from './dto/create-comment.dto.js';
import { CommentResponseDto } from './dto/comment-response.dto.js';
import { UpdateCommentDto } from './dto/update-comment.dto.js';

@Injectable()
export class CommentService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateCommentDto): Promise<CommentResponseDto> {
    return this.prisma.comment.create({
      data: data as unknown as Prisma.CommentCreateInput,
    }) as unknown as Promise<CommentResponseDto>;
  }

  findAll(): Promise<CommentResponseDto[]> {
    return this.prisma.comment.findMany() as unknown as Promise<
      CommentResponseDto[]
    >;
  }

  findOne(id: string): Promise<CommentResponseDto | null> {
    return this.prisma.comment.findUnique({
      where: { id },
    }) as unknown as Promise<CommentResponseDto | null>;
  }

  update(id: string, data: UpdateCommentDto): Promise<CommentResponseDto> {
    return this.prisma.comment.update({
      where: { id },
      data: data as unknown as Prisma.CommentUpdateInput,
    }) as unknown as Promise<CommentResponseDto>;
  }

  remove(id: string): Promise<CommentResponseDto> {
    return this.prisma.comment.delete({
      where: { id },
    }) as unknown as Promise<CommentResponseDto>;
  }
}
