// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { CreateCommentDto } from './dto/create-comment.dto.js';
import { CommentResponseDto } from './dto/comment-response.dto.js';
import { UpdateCommentDto } from './dto/update-comment.dto.js';

const relations = [] as const;

@Injectable()
export class CommentService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateCommentDto): Promise<CommentResponseDto> {
    return this.database.create('comment', data, relations);
  }

  findAll(): Promise<CommentResponseDto[]> {
    return this.database.findAll('comment', relations);
  }

  findOne(id: string): Promise<CommentResponseDto | null> {
    return this.database.findOne('comment', id, relations);
  }

  update(id: string, data: UpdateCommentDto): Promise<CommentResponseDto> {
    return this.database.update('comment', id, data, relations);
  }

  remove(id: string): Promise<CommentResponseDto> {
    return this.database.remove('comment', id, relations);
  }
}
