// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreatePermissionDto } from './dto/create-permission.dto.js';
import { PermissionResponseDto } from './dto/permission-response.dto.js';
import { UpdatePermissionDto } from './dto/update-permission.dto.js';

const relations = [
  {
    property: 'actions',
    table: 'action',
    isArray: true,
    readOnly: false,
  },
] as const;

@Injectable()
export class PermissionService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreatePermissionDto): Promise<PermissionResponseDto> {
    return this.database.create('permission', data, relations);
  }

  findAll(): Promise<PermissionResponseDto[]> {
    return this.database.findAll('permission', relations);
  }

  findOne(id: string): Promise<PermissionResponseDto | null> {
    return this.database.findOne('permission', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('permission', id, query);
  }

  update(
    id: string,
    data: UpdatePermissionDto,
  ): Promise<PermissionResponseDto> {
    return this.database.update('permission', id, data, relations);
  }

  remove(id: string): Promise<PermissionResponseDto> {
    return this.database.remove('permission', id, relations);
  }
}
