// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreatePermissionDto } from './dto/create-permission.dto.js';
import { PermissionResponseDto } from './dto/permission-response.dto.js';
import { UpdatePermissionDto } from './dto/update-permission.dto.js';

const permissionRelations = {
  actions: true,
} as const;

@Injectable()
export class PermissionService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreatePermissionDto): Promise<PermissionResponseDto> {
    return this.prisma.permission.create({
      data: data as unknown as Prisma.PermissionCreateInput,
      include: permissionRelations,
    }) as unknown as Promise<PermissionResponseDto>;
  }

  findAll(): Promise<PermissionResponseDto[]> {
    return this.prisma.permission.findMany({
      include: permissionRelations,
    }) as unknown as Promise<PermissionResponseDto[]>;
  }

  findOne(id: string): Promise<PermissionResponseDto | null> {
    return this.prisma.permission.findUnique({
      where: { id },
      include: permissionRelations,
    }) as unknown as Promise<PermissionResponseDto | null>;
  }

  update(
    id: string,
    data: UpdatePermissionDto,
  ): Promise<PermissionResponseDto> {
    return this.prisma.permission.update({
      where: { id },
      data: data as unknown as Prisma.PermissionUpdateInput,
      include: permissionRelations,
    }) as unknown as Promise<PermissionResponseDto>;
  }

  remove(id: string): Promise<PermissionResponseDto> {
    return this.prisma.permission.delete({
      where: { id },
      include: permissionRelations,
    }) as unknown as Promise<PermissionResponseDto>;
  }
}
