// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBody,
  ApiBadRequestResponse,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreatePermissionDto } from './dto/create-permission.dto.js';
import { PermissionResponseDto } from './dto/permission-response.dto.js';
import { UpdatePermissionDto } from './dto/update-permission.dto.js';
import { PermissionService } from './permission.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';

@ApiTags('permissions')
@Controller('permissions')
export class PermissionController {
  constructor(private readonly permissionService: PermissionService) {}

  @Post()
  @ApiOperation({
    operationId: 'createPermission',
    summary: 'Create a Permission.',
  })
  @ApiBody({ type: CreatePermissionDto })
  @ApiCreatedResponse({ type: PermissionResponseDto })
  create(@Body() data: CreatePermissionDto): Promise<PermissionResponseDto> {
    return this.permissionService.create(data);
  }

  @Get()
  @ApiOperation({
    operationId: 'listPermissions',
    summary: 'List Permission records.',
  })
  @ApiOkResponse({ type: PermissionResponseDto, isArray: true })
  findAll(): Promise<PermissionResponseDto[]> {
    return this.permissionService.findAll();
  }

  @Get(':id')
  @ApiOperation({
    operationId: 'getPermission',
    summary: 'Get a Permission by ID.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Permission ID.' })
  @ApiOkResponse({ type: PermissionResponseDto })
  @ApiNotFoundResponse({ description: 'Permission not found.' })
  async findOne(@Param('id') id: string): Promise<PermissionResponseDto> {
    const result = await this.permissionService.findOne(id);
    if (!result) throw new NotFoundException('Permission not found.');
    return result;
  }

  @Get(':id/relations')
  @ApiOperation({
    operationId: 'listPermissionRelations',
    summary: 'Query relationships associated with a Permission.',
  })
  @ApiParam({
    name: 'id',
    type: String,
    description: 'Permission ID (URL-encode slashes).',
  })
  @ApiOkResponse({ type: RelationshipResponseDto, isArray: true })
  @ApiBadRequestResponse({
    description: 'Invalid direction or equality filters.',
  })
  @ApiNotFoundResponse({ description: 'Permission not found.' })
  findRelations(
    @Param('id') id: string,
    @Query() query: RelationsQueryDto,
  ): Promise<RelationshipResponseDto[]> {
    return this.permissionService.findRelations(id, query);
  }

  @Patch(':id')
  @ApiOperation({
    operationId: 'updatePermission',
    summary: 'Update a Permission.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Permission ID.' })
  @ApiBody({ type: UpdatePermissionDto })
  @ApiOkResponse({ type: PermissionResponseDto })
  @ApiNotFoundResponse({ description: 'Permission not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdatePermissionDto,
  ): Promise<PermissionResponseDto> {
    return this.permissionService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    operationId: 'deletePermission',
    summary: 'Delete a Permission.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Permission ID.' })
  @ApiNoContentResponse({ description: 'Permission deleted.' })
  @ApiNotFoundResponse({ description: 'Permission not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.permissionService.remove(id);
  }
}
