// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { assertEntityType } from '../surreal/entity-type.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateGeographicAreaDto } from './dto/create-geographic-area.dto.js';
import { GeographicAreaResponseDto } from './dto/geographic-area-response.dto.js';
import { UpdateGeographicAreaDto } from './dto/update-geographic-area.dto.js';

const relations = [] as const;

@Injectable()
export class GeographicAreaService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateGeographicAreaDto): Promise<GeographicAreaResponseDto> {
    assertEntityType(data, 'Geographic Area');
    return this.database.create('geographic_area', data, relations);
  }

  findAll(): Promise<GeographicAreaResponseDto[]> {
    return this.database.findAll('geographic_area', relations);
  }

  findOne(id: string): Promise<GeographicAreaResponseDto | null> {
    return this.database.findOne('geographic_area', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('geographic_area', id, query);
  }

  update(
    id: string,
    data: UpdateGeographicAreaDto,
  ): Promise<GeographicAreaResponseDto> {
    assertEntityType(data, 'Geographic Area', true);
    return this.database.update('geographic_area', id, data, relations);
  }

  remove(id: string): Promise<GeographicAreaResponseDto> {
    return this.database.remove('geographic_area', id, relations);
  }
}
