// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateGeographicAreaDto } from './dto/create-geographic-area.dto.js';
import { GeographicAreaResponseDto } from './dto/geographic-area-response.dto.js';
import { UpdateGeographicAreaDto } from './dto/update-geographic-area.dto.js';

@Injectable()
export class GeographicAreaService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateGeographicAreaDto): Promise<GeographicAreaResponseDto> {
    return this.prisma.geographicArea.create({
      data: data as unknown as Prisma.GeographicAreaCreateInput,
    }) as unknown as Promise<GeographicAreaResponseDto>;
  }

  findAll(): Promise<GeographicAreaResponseDto[]> {
    return this.prisma.geographicArea.findMany() as unknown as Promise<
      GeographicAreaResponseDto[]
    >;
  }

  findOne(id: string): Promise<GeographicAreaResponseDto | null> {
    return this.prisma.geographicArea.findUnique({
      where: { id },
    }) as unknown as Promise<GeographicAreaResponseDto | null>;
  }

  update(
    id: string,
    data: UpdateGeographicAreaDto,
  ): Promise<GeographicAreaResponseDto> {
    return this.prisma.geographicArea.update({
      where: { id },
      data: data as unknown as Prisma.GeographicAreaUpdateInput,
    }) as unknown as Promise<GeographicAreaResponseDto>;
  }

  remove(id: string): Promise<GeographicAreaResponseDto> {
    return this.prisma.geographicArea.delete({
      where: { id },
    }) as unknown as Promise<GeographicAreaResponseDto>;
  }
}
