// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { GeographicAreaController } from './geographic-area.controller.js';
import { GeographicAreaService } from './geographic-area.service.js';

@Module({
  controllers: [GeographicAreaController],
  providers: [GeographicAreaService],
})
export class GeographicAreaModule {}
