// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
} from '@nestjs/common';
import {
  ApiBody,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateGeographicAreaDto } from './dto/create-geographic-area.dto.js';
import { GeographicAreaResponseDto } from './dto/geographic-area-response.dto.js';
import { UpdateGeographicAreaDto } from './dto/update-geographic-area.dto.js';
import { GeographicAreaService } from './geographic-area.service.js';

@ApiTags('geographic-areas')
@Controller('geographic-areas')
export class GeographicAreaController {
  constructor(private readonly geographicAreaService: GeographicAreaService) {}

  @Post()
  @ApiOperation({
    operationId: 'createGeographicArea',
    summary: 'Create a GeographicArea.',
  })
  @ApiBody({ type: CreateGeographicAreaDto })
  @ApiCreatedResponse({ type: GeographicAreaResponseDto })
  create(
    @Body() data: CreateGeographicAreaDto,
  ): Promise<GeographicAreaResponseDto> {
    return this.geographicAreaService.create(data);
  }

  @Get()
  @ApiOperation({
    operationId: 'listGeographicAreas',
    summary: 'List GeographicArea records.',
  })
  @ApiOkResponse({ type: GeographicAreaResponseDto, isArray: true })
  findAll(): Promise<GeographicAreaResponseDto[]> {
    return this.geographicAreaService.findAll();
  }

  @Get(':id')
  @ApiOperation({
    operationId: 'getGeographicArea',
    summary: 'Get a GeographicArea by ID.',
  })
  @ApiParam({ name: 'id', type: String, description: 'GeographicArea ID.' })
  @ApiOkResponse({ type: GeographicAreaResponseDto })
  @ApiNotFoundResponse({ description: 'GeographicArea not found.' })
  async findOne(@Param('id') id: string): Promise<GeographicAreaResponseDto> {
    const result = await this.geographicAreaService.findOne(id);
    if (!result) throw new NotFoundException('GeographicArea not found.');
    return result;
  }

  @Patch(':id')
  @ApiOperation({
    operationId: 'updateGeographicArea',
    summary: 'Update a GeographicArea.',
  })
  @ApiParam({ name: 'id', type: String, description: 'GeographicArea ID.' })
  @ApiBody({ type: UpdateGeographicAreaDto })
  @ApiOkResponse({ type: GeographicAreaResponseDto })
  @ApiNotFoundResponse({ description: 'GeographicArea not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateGeographicAreaDto,
  ): Promise<GeographicAreaResponseDto> {
    return this.geographicAreaService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    operationId: 'deleteGeographicArea',
    summary: 'Delete a GeographicArea.',
  })
  @ApiParam({ name: 'id', type: String, description: 'GeographicArea ID.' })
  @ApiNoContentResponse({ description: 'GeographicArea deleted.' })
  @ApiNotFoundResponse({ description: 'GeographicArea not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.geographicAreaService.remove(id);
  }
}
