// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { CreateChangeItemDto } from './dto/create-change-item.dto.js';
import { ChangeItemResponseDto } from './dto/change-item-response.dto.js';
import { UpdateChangeItemDto } from './dto/update-change-item.dto.js';

const relations = [] as const;

@Injectable()
export class ChangeItemService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateChangeItemDto): Promise<ChangeItemResponseDto> {
    return this.database.create('change_item', data, relations);
  }

  findAll(): Promise<ChangeItemResponseDto[]> {
    return this.database.findAll('change_item', relations);
  }

  findOne(id: string): Promise<ChangeItemResponseDto | null> {
    return this.database.findOne('change_item', id, relations);
  }

  update(
    id: string,
    data: UpdateChangeItemDto,
  ): Promise<ChangeItemResponseDto> {
    return this.database.update('change_item', id, data, relations);
  }

  remove(id: string): Promise<ChangeItemResponseDto> {
    return this.database.remove('change_item', id, relations);
  }
}
