// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { ChangeItemController } from './change-item.controller.js';
import { ChangeItemService } from './change-item.service.js';

@Module({
  controllers: [ChangeItemController],
  providers: [ChangeItemService],
})
export class ChangeItemModule {}
