// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateChangeItemDto } from './dto/create-change-item.dto.js';
import { ChangeItemResponseDto } from './dto/change-item-response.dto.js';
import { UpdateChangeItemDto } from './dto/update-change-item.dto.js';

@Injectable()
export class ChangeItemService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateChangeItemDto): Promise<ChangeItemResponseDto> {
    return this.prisma.changeItem.create({
      data: data as unknown as Prisma.ChangeItemCreateInput,
    }) as unknown as Promise<ChangeItemResponseDto>;
  }

  findAll(): Promise<ChangeItemResponseDto[]> {
    return this.prisma.changeItem.findMany() as unknown as Promise<
      ChangeItemResponseDto[]
    >;
  }

  findOne(id: string): Promise<ChangeItemResponseDto | null> {
    return this.prisma.changeItem.findUnique({
      where: { id },
    }) as unknown as Promise<ChangeItemResponseDto | null>;
  }

  update(
    id: string,
    data: UpdateChangeItemDto,
  ): Promise<ChangeItemResponseDto> {
    return this.prisma.changeItem.update({
      where: { id },
      data: data as unknown as Prisma.ChangeItemUpdateInput,
    }) as unknown as Promise<ChangeItemResponseDto>;
  }

  remove(id: string): Promise<ChangeItemResponseDto> {
    return this.prisma.changeItem.delete({
      where: { id },
    }) as unknown as Promise<ChangeItemResponseDto>;
  }
}
