// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { assertEntityType } from '../surreal/entity-type.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';

import { CreateRelationshipDto } from './dto/create-relationship.dto.js';
import { RelationshipResponseDto } from './dto/relationship-response.dto.js';
import { UpdateRelationshipDto } from './dto/update-relationship.dto.js';

const relations = [] as const;

@Injectable()
export class RelationshipService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateRelationshipDto): Promise<RelationshipResponseDto> {
    assertEntityType(data, 'Relationship');
    return this.database.createEdge('relationship', data, relations);
  }

  findAll(): Promise<RelationshipResponseDto[]> {
    return this.database.findAll('relationship', relations);
  }

  findOne(id: string): Promise<RelationshipResponseDto | null> {
    return this.database.findOne('relationship', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('relationship', id, query);
  }

  update(
    id: string,
    data: UpdateRelationshipDto,
  ): Promise<RelationshipResponseDto> {
    assertEntityType(data, 'Relationship', true);
    return this.database.updateEdge('relationship', id, data, relations);
  }

  remove(id: string): Promise<RelationshipResponseDto> {
    return this.database.remove('relationship', id, relations);
  }
}
