// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBody,
  ApiBadRequestResponse,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateRelationshipDto } from './dto/create-relationship.dto.js';
import { RelationshipResponseDto } from './dto/relationship-response.dto.js';
import { UpdateRelationshipDto } from './dto/update-relationship.dto.js';
import { RelationshipService } from './relationship.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';

@ApiTags('relationships')
@Controller('relationships')
export class RelationshipController {
  constructor(private readonly relationshipService: RelationshipService) {}

  @Post()
  @ApiOperation({
    operationId: 'createRelationship',
    summary: 'Create a Relationship.',
  })
  @ApiBody({ type: CreateRelationshipDto })
  @ApiCreatedResponse({ type: RelationshipResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType must match the entity schema title.',
  })
  create(
    @Body() data: CreateRelationshipDto,
  ): Promise<RelationshipResponseDto> {
    return this.relationshipService.create(data);
  }

  @Get()
  @ApiOperation({
    operationId: 'listRelationships',
    summary: 'List Relationship records.',
  })
  @ApiOkResponse({ type: RelationshipResponseDto, isArray: true })
  findAll(): Promise<RelationshipResponseDto[]> {
    return this.relationshipService.findAll();
  }

  @Get(':id')
  @ApiOperation({
    operationId: 'getRelationship',
    summary: 'Get a Relationship by ID.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Relationship ID.' })
  @ApiOkResponse({ type: RelationshipResponseDto })
  @ApiNotFoundResponse({ description: 'Relationship not found.' })
  async findOne(@Param('id') id: string): Promise<RelationshipResponseDto> {
    const result = await this.relationshipService.findOne(id);
    if (!result) throw new NotFoundException('Relationship not found.');
    return result;
  }

  @Get(':id/relations')
  @ApiOperation({
    operationId: 'listRelationshipRelations',
    summary: 'Query relationships associated with a Relationship.',
  })
  @ApiParam({
    name: 'id',
    type: String,
    description: 'Relationship ID (URL-encode slashes).',
  })
  @ApiOkResponse({ type: RelationshipResponseDto, isArray: true })
  @ApiBadRequestResponse({
    description: 'Invalid direction or equality filters.',
  })
  @ApiNotFoundResponse({ description: 'Relationship not found.' })
  findRelations(
    @Param('id') id: string,
    @Query() query: RelationsQueryDto,
  ): Promise<RelationshipResponseDto[]> {
    return this.relationshipService.findRelations(id, query);
  }

  @Patch(':id')
  @ApiOperation({
    operationId: 'updateRelationship',
    summary: 'Update a Relationship.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Relationship ID.' })
  @ApiBody({ type: UpdateRelationshipDto })
  @ApiOkResponse({ type: RelationshipResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType cannot change from the entity schema title.',
  })
  @ApiNotFoundResponse({ description: 'Relationship not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateRelationshipDto,
  ): Promise<RelationshipResponseDto> {
    return this.relationshipService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    operationId: 'deleteRelationship',
    summary: 'Delete a Relationship.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Relationship ID.' })
  @ApiNoContentResponse({ description: 'Relationship deleted.' })
  @ApiNotFoundResponse({ description: 'Relationship not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.relationshipService.remove(id);
  }
}
