// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { RelationshipController } from './relationship.controller.js';
import { RelationshipService } from './relationship.service.js';

@Module({
  controllers: [RelationshipController],
  providers: [RelationshipService],
})
export class RelationshipModule {}
