// Generated by scripts/generate-service.mjs.
import { Injectable } from '@nestjs/common';
import type { Member, Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';

@Injectable()
export class MemberService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: Prisma.MemberCreateInput): Promise<Member> {
    return this.prisma.member.create({ data });
  }

  findAll(): Promise<Member[]> {
    return this.prisma.member.findMany();
  }

  findOne(id: string): Promise<Member | null> {
    return this.prisma.member.findUnique({ where: { id } });
  }

  update(id: string, data: Prisma.MemberUpdateInput): Promise<Member> {
    return this.prisma.member.update({ where: { id }, data });
  }

  remove(id: string): Promise<Member> {
    return this.prisma.member.delete({ where: { id } });
  }
}
