// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
} from '@nestjs/common';
import {
  ApiBody,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateMemberDto } from './dto/create-member.dto.js';
import { MemberResponseDto } from './dto/member-response.dto.js';
import { UpdateMemberDto } from './dto/update-member.dto.js';
import { MemberService } from './member.service.js';

@ApiTags('members')
@Controller('members')
export class MemberController {
  constructor(private readonly memberService: MemberService) {}

  @Post()
  @ApiOperation({ operationId: 'createMember', summary: 'Create a Member.' })
  @ApiBody({ type: CreateMemberDto })
  @ApiCreatedResponse({ type: MemberResponseDto })
  create(@Body() data: CreateMemberDto): Promise<MemberResponseDto> {
    return this.memberService.create(data);
  }

  @Get()
  @ApiOperation({ operationId: 'listMembers', summary: 'List Member records.' })
  @ApiOkResponse({ type: MemberResponseDto, isArray: true })
  findAll(): Promise<MemberResponseDto[]> {
    return this.memberService.findAll();
  }

  @Get(':id')
  @ApiOperation({ operationId: 'getMember', summary: 'Get a Member by ID.' })
  @ApiParam({ name: 'id', type: String, description: 'Member ID.' })
  @ApiOkResponse({ type: MemberResponseDto })
  @ApiNotFoundResponse({ description: 'Member not found.' })
  async findOne(@Param('id') id: string): Promise<MemberResponseDto> {
    const result = await this.memberService.findOne(id);
    if (!result) throw new NotFoundException('Member not found.');
    return result;
  }

  @Patch(':id')
  @ApiOperation({ operationId: 'updateMember', summary: 'Update a Member.' })
  @ApiParam({ name: 'id', type: String, description: 'Member ID.' })
  @ApiBody({ type: UpdateMemberDto })
  @ApiOkResponse({ type: MemberResponseDto })
  @ApiNotFoundResponse({ description: 'Member not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateMemberDto,
  ): Promise<MemberResponseDto> {
    return this.memberService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ operationId: 'deleteMember', summary: 'Delete a Member.' })
  @ApiParam({ name: 'id', type: String, description: 'Member ID.' })
  @ApiNoContentResponse({ description: 'Member deleted.' })
  @ApiNotFoundResponse({ description: 'Member not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.memberService.remove(id);
  }
}
