// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateMemberDto } from './dto/create-member.dto.js';
import { MemberResponseDto } from './dto/member-response.dto.js';
import { UpdateMemberDto } from './dto/update-member.dto.js';

const memberRelations = {
  permissions: true,
  roles: true,
} as const;

@Injectable()
export class MemberService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateMemberDto): Promise<MemberResponseDto> {
    return this.prisma.member.create({
      data: data as unknown as Prisma.MemberCreateInput,
      include: memberRelations,
    }) as unknown as Promise<MemberResponseDto>;
  }

  findAll(): Promise<MemberResponseDto[]> {
    return this.prisma.member.findMany({
      include: memberRelations,
    }) as unknown as Promise<MemberResponseDto[]>;
  }

  findOne(id: string): Promise<MemberResponseDto | null> {
    return this.prisma.member.findUnique({
      where: { id },
      include: memberRelations,
    }) as unknown as Promise<MemberResponseDto | null>;
  }

  update(id: string, data: UpdateMemberDto): Promise<MemberResponseDto> {
    return this.prisma.member.update({
      where: { id },
      data: data as unknown as Prisma.MemberUpdateInput,
      include: memberRelations,
    }) as unknown as Promise<MemberResponseDto>;
  }

  remove(id: string): Promise<MemberResponseDto> {
    return this.prisma.member.delete({
      where: { id },
      include: memberRelations,
    }) as unknown as Promise<MemberResponseDto>;
  }
}
