// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { CreateMemberDto } from './dto/create-member.dto.js';
import { MemberResponseDto } from './dto/member-response.dto.js';
import { UpdateMemberDto } from './dto/update-member.dto.js';

const relations = [
  {
    property: 'permissions',
    table: 'permission',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'roles',
    table: 'role',
    isArray: true,
    readOnly: true,
  },
] as const;

@Injectable()
export class MemberService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateMemberDto): Promise<MemberResponseDto> {
    return this.database.create('member', data, relations);
  }

  findAll(): Promise<MemberResponseDto[]> {
    return this.database.findAll('member', relations);
  }

  findOne(id: string): Promise<MemberResponseDto | null> {
    return this.database.findOne('member', id, relations);
  }

  update(id: string, data: UpdateMemberDto): Promise<MemberResponseDto> {
    return this.database.update('member', id, data, relations);
  }

  remove(id: string): Promise<MemberResponseDto> {
    return this.database.remove('member', id, relations);
  }
}
