// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { RelationshipTypeController } from './relationship-type.controller.js';
import { RelationshipTypeService } from './relationship-type.service.js';

@Module({
  controllers: [RelationshipTypeController],
  providers: [RelationshipTypeService],
})
export class RelationshipTypeModule {}
