// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
} from '@nestjs/common';
import {
  ApiBody,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateRelationshipTypeDto } from './dto/create-relationship-type.dto.js';
import { RelationshipTypeResponseDto } from './dto/relationship-type-response.dto.js';
import { UpdateRelationshipTypeDto } from './dto/update-relationship-type.dto.js';
import { RelationshipTypeService } from './relationship-type.service.js';

@ApiTags('relationship-types')
@Controller('relationship-types')
export class RelationshipTypeController {
  constructor(
    private readonly relationshipTypeService: RelationshipTypeService,
  ) {}

  @Post()
  @ApiOperation({
    operationId: 'createRelationshipType',
    summary: 'Create a RelationshipType.',
  })
  @ApiBody({ type: CreateRelationshipTypeDto })
  @ApiCreatedResponse({ type: RelationshipTypeResponseDto })
  create(
    @Body() data: CreateRelationshipTypeDto,
  ): Promise<RelationshipTypeResponseDto> {
    return this.relationshipTypeService.create(data);
  }

  @Get()
  @ApiOperation({
    operationId: 'listRelationshipTypes',
    summary: 'List RelationshipType records.',
  })
  @ApiOkResponse({ type: RelationshipTypeResponseDto, isArray: true })
  findAll(): Promise<RelationshipTypeResponseDto[]> {
    return this.relationshipTypeService.findAll();
  }

  @Get(':id')
  @ApiOperation({
    operationId: 'getRelationshipType',
    summary: 'Get a RelationshipType by ID.',
  })
  @ApiParam({ name: 'id', type: String, description: 'RelationshipType ID.' })
  @ApiOkResponse({ type: RelationshipTypeResponseDto })
  @ApiNotFoundResponse({ description: 'RelationshipType not found.' })
  async findOne(@Param('id') id: string): Promise<RelationshipTypeResponseDto> {
    const result = await this.relationshipTypeService.findOne(id);
    if (!result) throw new NotFoundException('RelationshipType not found.');
    return result;
  }

  @Patch(':id')
  @ApiOperation({
    operationId: 'updateRelationshipType',
    summary: 'Update a RelationshipType.',
  })
  @ApiParam({ name: 'id', type: String, description: 'RelationshipType ID.' })
  @ApiBody({ type: UpdateRelationshipTypeDto })
  @ApiOkResponse({ type: RelationshipTypeResponseDto })
  @ApiNotFoundResponse({ description: 'RelationshipType not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateRelationshipTypeDto,
  ): Promise<RelationshipTypeResponseDto> {
    return this.relationshipTypeService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    operationId: 'deleteRelationshipType',
    summary: 'Delete a RelationshipType.',
  })
  @ApiParam({ name: 'id', type: String, description: 'RelationshipType ID.' })
  @ApiNoContentResponse({ description: 'RelationshipType deleted.' })
  @ApiNotFoundResponse({ description: 'RelationshipType not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.relationshipTypeService.remove(id);
  }
}
