// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { CreateRelationshipTypeDto } from './dto/create-relationship-type.dto.js';
import { RelationshipTypeResponseDto } from './dto/relationship-type-response.dto.js';
import { UpdateRelationshipTypeDto } from './dto/update-relationship-type.dto.js';

const relations = [] as const;

@Injectable()
export class RelationshipTypeService {
  constructor(private readonly database: SurrealService) {}

  create(
    data: CreateRelationshipTypeDto,
  ): Promise<RelationshipTypeResponseDto> {
    return this.database.create('relationship_type', data, relations);
  }

  findAll(): Promise<RelationshipTypeResponseDto[]> {
    return this.database.findAll('relationship_type', relations);
  }

  findOne(id: string): Promise<RelationshipTypeResponseDto | null> {
    return this.database.findOne('relationship_type', id, relations);
  }

  update(
    id: string,
    data: UpdateRelationshipTypeDto,
  ): Promise<RelationshipTypeResponseDto> {
    return this.database.update('relationship_type', id, data, relations);
  }

  remove(id: string): Promise<RelationshipTypeResponseDto> {
    return this.database.remove('relationship_type', id, relations);
  }
}
