// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateProtocolDto } from './dto/create-protocol.dto.js';
import { ProtocolResponseDto } from './dto/protocol-response.dto.js';
import { UpdateProtocolDto } from './dto/update-protocol.dto.js';

@Injectable()
export class ProtocolService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateProtocolDto): Promise<ProtocolResponseDto> {
    return this.prisma.protocol.create({
      data: data as unknown as Prisma.ProtocolCreateInput,
    }) as unknown as Promise<ProtocolResponseDto>;
  }

  findAll(): Promise<ProtocolResponseDto[]> {
    return this.prisma.protocol.findMany() as unknown as Promise<
      ProtocolResponseDto[]
    >;
  }

  findOne(id: string): Promise<ProtocolResponseDto | null> {
    return this.prisma.protocol.findUnique({
      where: { id },
    }) as unknown as Promise<ProtocolResponseDto | null>;
  }

  update(id: string, data: UpdateProtocolDto): Promise<ProtocolResponseDto> {
    return this.prisma.protocol.update({
      where: { id },
      data: data as unknown as Prisma.ProtocolUpdateInput,
    }) as unknown as Promise<ProtocolResponseDto>;
  }

  remove(id: string): Promise<ProtocolResponseDto> {
    return this.prisma.protocol.delete({
      where: { id },
    }) as unknown as Promise<ProtocolResponseDto>;
  }
}
