// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateProtocolDto } from './dto/create-protocol.dto.js';
import { ProtocolResponseDto } from './dto/protocol-response.dto.js';
import { UpdateProtocolDto } from './dto/update-protocol.dto.js';

const relations = [] as const;

@Injectable()
export class ProtocolService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateProtocolDto): Promise<ProtocolResponseDto> {
    return this.database.create('protocol', data, relations);
  }

  findAll(): Promise<ProtocolResponseDto[]> {
    return this.database.findAll('protocol', relations);
  }

  findOne(id: string): Promise<ProtocolResponseDto | null> {
    return this.database.findOne('protocol', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('protocol', id, query);
  }

  update(id: string, data: UpdateProtocolDto): Promise<ProtocolResponseDto> {
    return this.database.update('protocol', id, data, relations);
  }

  remove(id: string): Promise<ProtocolResponseDto> {
    return this.database.remove('protocol', id, relations);
  }
}
