import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { PersonalityParameters } from "../src/game/personality.js";
import { formativeExperiences } from "../src/generation/pools/formative-experiences.js";
import { traitPool } from "../src/generation/pools/trait-pool.js";
import { worldviewPool } from "../src/generation/pools/worldview-pool.js";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(packageRoot, "src/fake/personalities.ts");

function parseCount(value: string | undefined): number {
  const count = Number(value);

  if (!Number.isSafeInteger(count) || count < 0) {
    throw new Error(
      "Personality count must be a non-negative integer. Usage: pnpm personalities:generate <count>",
    );
  }

  return count;
}

// Generic selection keeps every pool subject to the same empty-pool guard.
function pickRandom<T>(pool: readonly T[], poolName: string): T {
  if (pool.length === 0) {
    throw new Error(`${poolName} cannot be empty.`);
  }

  return pool[Math.floor(Math.random() * pool.length)]!;
}

// Sampling without replacement prevents duplicate experiences or traits.
function pickRandomMany<T>(
  pool: readonly T[],
  poolName: string,
  maxCount = 3,
): T[] {
  if (pool.length === 0) {
    throw new Error(`${poolName} cannot be empty.`);
  }

  const available = [...pool];
  const count = Math.floor(Math.random() * Math.min(maxCount, pool.length)) + 1;

  return Array.from({ length: count }, () => {
    const index = Math.floor(Math.random() * available.length);
    return available.splice(index, 1)[0]!;
  });
}

function formatParameters(value: unknown): string {
  return JSON.stringify(value, null, 2).replace(/\n/g, "\n  ");
}

function createPersonalitySource(count: number): string {
  const personalities = Array.from({ length: count }, () => {
    const experiences = pickRandomMany(
      formativeExperiences,
      "formativeExperiences",
    );
    const traits = pickRandomMany(traitPool, "traitPool");
    const worldview = pickRandom(worldviewPool, "worldviewPool");
    const parameters: PersonalityParameters = {
      formativeExperiences: experiences,
      traits,
      worldview,
    };

    return `  new Personality(${formatParameters(parameters)})`;
  });

  return `// GENERATED by scripts/generate-personalities.ts. Do not edit by hand.\nimport { Personality } from "../game/personality.js";\n\nexport const personalities: Personality[] = [\n${personalities.join(",\n")}\n];\n`;
}

async function main(): Promise<void> {
  const count = parseCount(process.argv[2]);

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, createPersonalitySource(count), "utf8");
  console.log(`Generated ${count} personalities in ${outputPath}`);
}

await main();
