// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBody,
  ApiBadRequestResponse,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateChangeDto } from './dto/create-change.dto.js';
import { ChangeResponseDto } from './dto/change-response.dto.js';
import { UpdateChangeDto } from './dto/update-change.dto.js';
import { ChangeService } from './change.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';

@ApiTags('changes')
@Controller('changes')
export class ChangeController {
  constructor(private readonly changeService: ChangeService) {}

  @Post()
  @ApiOperation({ operationId: 'createChange', summary: 'Create a Change.' })
  @ApiBody({ type: CreateChangeDto })
  @ApiCreatedResponse({ type: ChangeResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType must match the entity schema title.',
  })
  create(@Body() data: CreateChangeDto): Promise<ChangeResponseDto> {
    return this.changeService.create(data);
  }

  @Get()
  @ApiOperation({ operationId: 'listChanges', summary: 'List Change records.' })
  @ApiOkResponse({ type: ChangeResponseDto, isArray: true })
  findAll(): Promise<ChangeResponseDto[]> {
    return this.changeService.findAll();
  }

  @Get(':id')
  @ApiOperation({ operationId: 'getChange', summary: 'Get a Change by ID.' })
  @ApiParam({ name: 'id', type: String, description: 'Change ID.' })
  @ApiOkResponse({ type: ChangeResponseDto })
  @ApiNotFoundResponse({ description: 'Change not found.' })
  async findOne(@Param('id') id: string): Promise<ChangeResponseDto> {
    const result = await this.changeService.findOne(id);
    if (!result) throw new NotFoundException('Change not found.');
    return result;
  }

  @Get(':id/relations')
  @ApiOperation({
    operationId: 'listChangeRelations',
    summary: 'Query relationships associated with a Change.',
  })
  @ApiParam({
    name: 'id',
    type: String,
    description: 'Change ID (URL-encode slashes).',
  })
  @ApiOkResponse({ type: RelationshipResponseDto, isArray: true })
  @ApiBadRequestResponse({
    description: 'Invalid direction or equality filters.',
  })
  @ApiNotFoundResponse({ description: 'Change not found.' })
  findRelations(
    @Param('id') id: string,
    @Query() query: RelationsQueryDto,
  ): Promise<RelationshipResponseDto[]> {
    return this.changeService.findRelations(id, query);
  }

  @Patch(':id')
  @ApiOperation({ operationId: 'updateChange', summary: 'Update a Change.' })
  @ApiParam({ name: 'id', type: String, description: 'Change ID.' })
  @ApiBody({ type: UpdateChangeDto })
  @ApiOkResponse({ type: ChangeResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType cannot change from the entity schema title.',
  })
  @ApiNotFoundResponse({ description: 'Change not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateChangeDto,
  ): Promise<ChangeResponseDto> {
    return this.changeService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ operationId: 'deleteChange', summary: 'Delete a Change.' })
  @ApiParam({ name: 'id', type: String, description: 'Change ID.' })
  @ApiNoContentResponse({ description: 'Change deleted.' })
  @ApiNotFoundResponse({ description: 'Change not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.changeService.remove(id);
  }
}
