// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { assertEntityType } from '../surreal/entity-type.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateChangeDto } from './dto/create-change.dto.js';
import { ChangeResponseDto } from './dto/change-response.dto.js';
import { UpdateChangeDto } from './dto/update-change.dto.js';

const relations = [
  {
    property: 'authors',
    table: 'member',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'changes',
    table: 'change_item',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'comments',
    table: 'comment',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'decision',
    table: 'decision',
    isArray: false,
    readOnly: false,
  },
  {
    property: 'mainAuthor',
    table: 'member',
    isArray: false,
    readOnly: false,
  },
  {
    property: 'reviewComments',
    table: 'review_comment',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'reviewers',
    table: 'member',
    isArray: true,
    readOnly: false,
  },
] as const;

@Injectable()
export class ChangeService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateChangeDto): Promise<ChangeResponseDto> {
    assertEntityType(data, 'Change');
    return this.database.create('change', data, relations);
  }

  findAll(): Promise<ChangeResponseDto[]> {
    return this.database.findAll('change', relations);
  }

  findOne(id: string): Promise<ChangeResponseDto | null> {
    return this.database.findOne('change', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('change', id, query);
  }

  update(id: string, data: UpdateChangeDto): Promise<ChangeResponseDto> {
    assertEntityType(data, 'Change', true);
    return this.database.update('change', id, data, relations);
  }

  remove(id: string): Promise<ChangeResponseDto> {
    return this.database.remove('change', id, relations);
  }
}
