// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateChangeDto } from './dto/create-change.dto.js';
import { ChangeResponseDto } from './dto/change-response.dto.js';
import { UpdateChangeDto } from './dto/update-change.dto.js';

const changeRelations = {
  authors: true,
  changes: true,
  comments: true,
  decision: true,
  mainAuthor: true,
  reviewComments: true,
  reviewers: true,
} as const;

// API relations are expanded entities; Prisma requires nested relation operations.
function toChangeCreateInput(data: CreateChangeDto): Prisma.ChangeCreateInput {
  const prismaData: Record<string, unknown> = { ...data };
  if (data.authors !== undefined) {
    prismaData.authors = { connect: data.authors.map(({ id }) => ({ id })) };
  }
  if (data.changes !== undefined) {
    prismaData.changes = { connect: data.changes.map(({ id }) => ({ id })) };
  }
  if (data.comments !== undefined) {
    prismaData.comments = { connect: data.comments.map(({ id }) => ({ id })) };
  }
  if (data.decision !== undefined) {
    delete prismaData.decisionRelationId;
    prismaData.decision = { connect: { id: data.decision.id } };
  }
  if (data.mainAuthor !== undefined) {
    delete prismaData.mainAuthorId;
    prismaData.mainAuthor = { connect: { id: data.mainAuthor.id } };
  }
  if (data.reviewComments !== undefined) {
    prismaData.reviewComments = {
      connect: data.reviewComments.map(({ id }) => ({ id })),
    };
  }
  if (data.reviewers !== undefined) {
    prismaData.reviewers = {
      connect: data.reviewers.map(({ id }) => ({ id })),
    };
  }
  return prismaData as unknown as Prisma.ChangeCreateInput;
}

function toChangeUpdateInput(data: UpdateChangeDto): Prisma.ChangeUpdateInput {
  const prismaData: Record<string, unknown> = { ...data };
  if (data.authors !== undefined) {
    prismaData.authors = { set: data.authors.map(({ id }) => ({ id })) };
  }
  if (data.changes !== undefined) {
    prismaData.changes = { set: data.changes.map(({ id }) => ({ id })) };
  }
  if (data.comments !== undefined) {
    prismaData.comments = { set: data.comments.map(({ id }) => ({ id })) };
  }
  if (data.decision !== undefined) {
    delete prismaData.decisionRelationId;
    prismaData.decision = { connect: { id: data.decision.id } };
  }
  if (data.mainAuthor !== undefined) {
    delete prismaData.mainAuthorId;
    prismaData.mainAuthor = { connect: { id: data.mainAuthor.id } };
  }
  if (data.reviewComments !== undefined) {
    prismaData.reviewComments = {
      set: data.reviewComments.map(({ id }) => ({ id })),
    };
  }
  if (data.reviewers !== undefined) {
    prismaData.reviewers = { set: data.reviewers.map(({ id }) => ({ id })) };
  }
  return prismaData as unknown as Prisma.ChangeUpdateInput;
}

@Injectable()
export class ChangeService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateChangeDto): Promise<ChangeResponseDto> {
    return this.prisma.change.create({
      data: toChangeCreateInput(data),
      include: changeRelations,
    }) as unknown as Promise<ChangeResponseDto>;
  }

  findAll(): Promise<ChangeResponseDto[]> {
    return this.prisma.change.findMany({
      include: changeRelations,
    }) as unknown as Promise<ChangeResponseDto[]>;
  }

  findOne(id: string): Promise<ChangeResponseDto | null> {
    return this.prisma.change.findUnique({
      where: { id },
      include: changeRelations,
    }) as unknown as Promise<ChangeResponseDto | null>;
  }

  update(id: string, data: UpdateChangeDto): Promise<ChangeResponseDto> {
    return this.prisma.change.update({
      where: { id },
      data: toChangeUpdateInput(data),
      include: changeRelations,
    }) as unknown as Promise<ChangeResponseDto>;
  }

  remove(id: string): Promise<ChangeResponseDto> {
    return this.prisma.change.delete({
      where: { id },
      include: changeRelations,
    }) as unknown as Promise<ChangeResponseDto>;
  }
}
