// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateChangeDto } from './dto/create-change.dto.js';
import { ChangeResponseDto } from './dto/change-response.dto.js';
import { UpdateChangeDto } from './dto/update-change.dto.js';

const changeRelations = {
  authors: true,
  changes: true,
  comments: true,
  decision: true,
  mainAuthor: true,
  reviewComments: true,
  reviewers: true,
} as const;

@Injectable()
export class ChangeService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateChangeDto): Promise<ChangeResponseDto> {
    return this.prisma.change.create({
      data: data as unknown as Prisma.ChangeCreateInput,
      include: changeRelations,
    }) as unknown as Promise<ChangeResponseDto>;
  }

  findAll(): Promise<ChangeResponseDto[]> {
    return this.prisma.change.findMany({
      include: changeRelations,
    }) as unknown as Promise<ChangeResponseDto[]>;
  }

  findOne(id: string): Promise<ChangeResponseDto | null> {
    return this.prisma.change.findUnique({
      where: { id },
      include: changeRelations,
    }) as unknown as Promise<ChangeResponseDto | null>;
  }

  update(id: string, data: UpdateChangeDto): Promise<ChangeResponseDto> {
    return this.prisma.change.update({
      where: { id },
      data: data as unknown as Prisma.ChangeUpdateInput,
      include: changeRelations,
    }) as unknown as Promise<ChangeResponseDto>;
  }

  remove(id: string): Promise<ChangeResponseDto> {
    return this.prisma.change.delete({
      where: { id },
      include: changeRelations,
    }) as unknown as Promise<ChangeResponseDto>;
  }
}
