#!/usr/bin/env node

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const apiRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const workspaceRoot = resolve(apiRoot, '..');
const entitiesRoot = join(workspaceRoot, 'ifs-standards', 'src', 'entities');
const prismaSchemaPath = join(apiRoot, 'prisma', 'schema.prisma');
const generateDtosPath = join(apiRoot, 'scripts', 'generate-dtos.mjs');
const generatedMarker = '// Generated by scripts/generate-service.mjs.';

function usage(message) {
  if (message) console.error(`Error: ${message}\n`);
  console.error(
    'Usage: pnpm --filter prototype-api service:generate <entity-name> [--skip-format]',
  );
  process.exitCode = message ? 1 : 0;
}

function kebabCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^A-Za-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

function lowerCamelCase(value) {
  return value[0].toLowerCase() + value.slice(1);
}

function readEntity(entityInput) {
  if (!entityInput || !/^[A-Za-z][A-Za-z0-9-]*$/.test(entityInput)) {
    throw new Error(`Invalid entity name: ${entityInput || '(missing)'}`);
  }

  const entityName = kebabCase(entityInput);
  const schemaPath = join(
    entitiesRoot,
    entityName,
    `${entityName}.schema.json`,
  );
  if (!existsSync(schemaPath)) {
    throw new Error(
      `Entity "${entityInput}" is not defined in IFS standards (expected ${schemaPath}).`,
    );
  }

  let schema;
  try {
    schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
  } catch (error) {
    throw new Error(
      `Could not read entity schema ${schemaPath}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  if (
    schema.type !== 'object' ||
    typeof schema.title !== 'string' ||
    !/^[A-Za-z][A-Za-z0-9]*$/.test(schema.title)
  ) {
    throw new Error(
      `Entity schema ${schemaPath} must define an object with a valid title.`,
    );
  }

  return { entityName, modelName: schema.title, schemaPath };
}

function expectedDtos(entityName, modelName) {
  const dtoRoot = join(apiRoot, 'src', entityName, 'dto');
  return [
    {
      path: join(dtoRoot, `create-${entityName}.dto.ts`),
      className: `Create${modelName}Dto`,
    },
    {
      path: join(dtoRoot, `update-${entityName}.dto.ts`),
      className: `Update${modelName}Dto`,
    },
    {
      path: join(dtoRoot, `${entityName}-response.dto.ts`),
      className: `${modelName}ResponseDto`,
    },
  ];
}

function missingDtos(entityName, modelName) {
  return expectedDtos(entityName, modelName).filter(({ path, className }) => {
    if (!existsSync(path)) return true;
    const source = readFileSync(path, 'utf8');
    return !new RegExp(`export\\s+class\\s+${className}\\b`).test(source);
  });
}

function ensureDtos(entityName, modelName) {
  let missing = missingDtos(entityName, modelName);
  if (!missing.length) return false;

  console.log(
    `Missing DTOs for ${modelName}; generating DTO artifacts for all IFS entities...`,
  );
  execFileSync(process.execPath, [generateDtosPath], {
    cwd: apiRoot,
    stdio: 'inherit',
  });

  missing = missingDtos(entityName, modelName);
  if (missing.length) {
    throw new Error(
      `DTO generation completed but these DTOs are still missing or invalid: ${missing
        .map(({ path }) => relative(workspaceRoot, path))
        .join(', ')}`,
    );
  }
  return true;
}

function assertPrismaModel(modelName) {
  if (!existsSync(prismaSchemaPath)) {
    throw new Error(`Prisma schema not found: ${prismaSchemaPath}`);
  }
  const prismaSchema = readFileSync(prismaSchemaPath, 'utf8');
  if (!new RegExp(`(^|\\n)model\\s+${modelName}\\s*\\{`).test(prismaSchema)) {
    throw new Error(
      `Prisma model ${modelName} is missing. Run the DTO generator before generating its service.`,
    );
  }
}

function renderService(entityName, modelName) {
  const delegateName = lowerCamelCase(modelName);
  return `${generatedMarker}
import { Injectable } from '@nestjs/common';
import type { ${modelName}, Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';

@Injectable()
export class ${modelName}Service {
  constructor(private readonly prisma: PrismaService) {}

  create(data: Prisma.${modelName}CreateInput): Promise<${modelName}> {
    return this.prisma.${delegateName}.create({ data });
  }

  findAll(): Promise<${modelName}[]> {
    return this.prisma.${delegateName}.findMany();
  }

  findOne(id: string): Promise<${modelName} | null> {
    return this.prisma.${delegateName}.findUnique({ where: { id } });
  }

  update(id: string, data: Prisma.${modelName}UpdateInput): Promise<${modelName}> {
    return this.prisma.${delegateName}.update({ where: { id }, data });
  }

  remove(id: string): Promise<${modelName}> {
    return this.prisma.${delegateName}.delete({ where: { id } });
  }
}
`;
}

export function generateService(entityInput, options = {}) {
  const { entityName, modelName, schemaPath } = readEntity(entityInput);
  const generatedDtos = ensureDtos(entityName, modelName);
  assertPrismaModel(modelName);

  const serviceDirectory = join(apiRoot, 'src', entityName);
  const servicePath = join(serviceDirectory, `${entityName}.service.ts`);
  const source = renderService(entityName, modelName);

  if (existsSync(servicePath)) {
    const existing = readFileSync(servicePath, 'utf8');
    if (!existing.startsWith(generatedMarker)) {
      throw new Error(
        `Refusing to overwrite service not managed by this generator: ${servicePath}`,
      );
    }
  }

  mkdirSync(serviceDirectory, { recursive: true });
  writeFileSync(servicePath, source);

  if (!options.skipFormat) {
    execFileSync('pnpm', ['exec', 'prettier', '--write', servicePath], {
      cwd: apiRoot,
      stdio: 'inherit',
    });
  }

  return { entityName, modelName, schemaPath, servicePath, generatedDtos };
}

function main() {
  const args = process.argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) return usage();

  const allowedFlags = new Set(['--skip-format']);
  const unknownFlag = args.find(
    (arg) => arg.startsWith('-') && !allowedFlags.has(arg),
  );
  if (unknownFlag) return usage(`Unknown option: ${unknownFlag}`);

  const positional = args.filter((arg) => !arg.startsWith('--'));
  if (positional.length !== 1)
    return usage('Expected exactly one entity name.');

  try {
    const result = generateService(positional[0], {
      skipFormat: args.includes('--skip-format'),
    });
    if (result.generatedDtos) console.log('Generated missing DTOs.');
    console.log(
      `Generated ${result.modelName}Service in ${relative(workspaceRoot, result.servicePath)}`,
    );
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
)
  main();
