// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { MemberModule } from './member/member.module.js';

@Module({
  imports: [MemberModule],
})
export class GeneratedResourcesModule {}
