// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { ActionModule } from './action/action.module.js';
import { ChangeModule } from './change/change.module.js';
import { ChangeItemModule } from './change-item/change-item.module.js';
import { CommentModule } from './comment/comment.module.js';
import { DecisionModule } from './decision/decision.module.js';
import { DelegationModule } from './delegation/delegation.module.js';
import { LabelModule } from './label/label.module.js';
import { MemberModule } from './member/member.module.js';
import { PermissionModule } from './permission/permission.module.js';
import { ProtocolModule } from './protocol/protocol.module.js';
import { ReviewCommentModule } from './review-comment/review-comment.module.js';
import { RoleModule } from './role/role.module.js';
import { RuleModule } from './rule/rule.module.js';
import { ScopeModule } from './scope/scope.module.js';
import { VoteModule } from './vote/vote.module.js';

@Module({
  imports: [
    ActionModule,
    ChangeModule,
    ChangeItemModule,
    CommentModule,
    DecisionModule,
    DelegationModule,
    LabelModule,
    MemberModule,
    PermissionModule,
    ProtocolModule,
    ReviewCommentModule,
    RoleModule,
    RuleModule,
    ScopeModule,
    VoteModule,
  ],
})
export class GeneratedResourcesModule {}
