// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreatePlaceDto } from './dto/create-place.dto.js';
import { PlaceResponseDto } from './dto/place-response.dto.js';
import { UpdatePlaceDto } from './dto/update-place.dto.js';

const placeRelations = {
  geographicArea: true,
  roles: true,
} as const;

// API relations are expanded entities; Prisma requires nested relation operations.
function toPlaceCreateInput(data: CreatePlaceDto): Prisma.PlaceCreateInput {
  const prismaData: Record<string, unknown> = { ...data };
  if (data.geographicArea !== undefined) {
    delete prismaData.geographicAreaRelationId;
    prismaData.geographicArea = { connect: { id: data.geographicArea.id } };
  }
  if (data.roles !== undefined) {
    prismaData.roles = { connect: data.roles.map(({ id }) => ({ id })) };
  }
  return prismaData as unknown as Prisma.PlaceCreateInput;
}

function toPlaceUpdateInput(data: UpdatePlaceDto): Prisma.PlaceUpdateInput {
  const prismaData: Record<string, unknown> = { ...data };
  if (data.geographicArea !== undefined) {
    delete prismaData.geographicAreaRelationId;
    prismaData.geographicArea = { connect: { id: data.geographicArea.id } };
  }
  if (data.roles !== undefined) {
    prismaData.roles = { set: data.roles.map(({ id }) => ({ id })) };
  }
  return prismaData as unknown as Prisma.PlaceUpdateInput;
}

@Injectable()
export class PlaceService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreatePlaceDto): Promise<PlaceResponseDto> {
    return this.prisma.place.create({
      data: toPlaceCreateInput(data),
      include: placeRelations,
    }) as unknown as Promise<PlaceResponseDto>;
  }

  findAll(): Promise<PlaceResponseDto[]> {
    return this.prisma.place.findMany({
      include: placeRelations,
    }) as unknown as Promise<PlaceResponseDto[]>;
  }

  findOne(id: string): Promise<PlaceResponseDto | null> {
    return this.prisma.place.findUnique({
      where: { id },
      include: placeRelations,
    }) as unknown as Promise<PlaceResponseDto | null>;
  }

  update(id: string, data: UpdatePlaceDto): Promise<PlaceResponseDto> {
    return this.prisma.place.update({
      where: { id },
      data: toPlaceUpdateInput(data),
      include: placeRelations,
    }) as unknown as Promise<PlaceResponseDto>;
  }

  remove(id: string): Promise<PlaceResponseDto> {
    return this.prisma.place.delete({
      where: { id },
      include: placeRelations,
    }) as unknown as Promise<PlaceResponseDto>;
  }
}
