// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
} from '@nestjs/common';
import {
  ApiBody,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreatePlaceDto } from './dto/create-place.dto.js';
import { PlaceResponseDto } from './dto/place-response.dto.js';
import { UpdatePlaceDto } from './dto/update-place.dto.js';
import { PlaceService } from './place.service.js';

@ApiTags('places')
@Controller('places')
export class PlaceController {
  constructor(private readonly placeService: PlaceService) {}

  @Post()
  @ApiOperation({ operationId: 'createPlace', summary: 'Create a Place.' })
  @ApiBody({ type: CreatePlaceDto })
  @ApiCreatedResponse({ type: PlaceResponseDto })
  create(@Body() data: CreatePlaceDto): Promise<PlaceResponseDto> {
    return this.placeService.create(data);
  }

  @Get()
  @ApiOperation({ operationId: 'listPlaces', summary: 'List Place records.' })
  @ApiOkResponse({ type: PlaceResponseDto, isArray: true })
  findAll(): Promise<PlaceResponseDto[]> {
    return this.placeService.findAll();
  }

  @Get(':id')
  @ApiOperation({ operationId: 'getPlace', summary: 'Get a Place by ID.' })
  @ApiParam({ name: 'id', type: String, description: 'Place ID.' })
  @ApiOkResponse({ type: PlaceResponseDto })
  @ApiNotFoundResponse({ description: 'Place not found.' })
  async findOne(@Param('id') id: string): Promise<PlaceResponseDto> {
    const result = await this.placeService.findOne(id);
    if (!result) throw new NotFoundException('Place not found.');
    return result;
  }

  @Patch(':id')
  @ApiOperation({ operationId: 'updatePlace', summary: 'Update a Place.' })
  @ApiParam({ name: 'id', type: String, description: 'Place ID.' })
  @ApiBody({ type: UpdatePlaceDto })
  @ApiOkResponse({ type: PlaceResponseDto })
  @ApiNotFoundResponse({ description: 'Place not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdatePlaceDto,
  ): Promise<PlaceResponseDto> {
    return this.placeService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ operationId: 'deletePlace', summary: 'Delete a Place.' })
  @ApiParam({ name: 'id', type: String, description: 'Place ID.' })
  @ApiNoContentResponse({ description: 'Place deleted.' })
  @ApiNotFoundResponse({ description: 'Place not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.placeService.remove(id);
  }
}
