// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { CreatePlaceDto } from './dto/create-place.dto.js';
import { PlaceResponseDto } from './dto/place-response.dto.js';
import { UpdatePlaceDto } from './dto/update-place.dto.js';

const relations = [
  {
    property: 'geographicArea',
    table: 'geographic_area',
    isArray: false,
    readOnly: false,
  },
  {
    property: 'roles',
    table: 'role',
    isArray: true,
    readOnly: false,
  },
] as const;

@Injectable()
export class PlaceService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreatePlaceDto): Promise<PlaceResponseDto> {
    return this.database.create('place', data, relations);
  }

  findAll(): Promise<PlaceResponseDto[]> {
    return this.database.findAll('place', relations);
  }

  findOne(id: string): Promise<PlaceResponseDto | null> {
    return this.database.findOne('place', id, relations);
  }

  update(id: string, data: UpdatePlaceDto): Promise<PlaceResponseDto> {
    return this.database.update('place', id, data, relations);
  }

  remove(id: string): Promise<PlaceResponseDto> {
    return this.database.remove('place', id, relations);
  }
}
