// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateDecisionDto } from './dto/create-decision.dto.js';
import { DecisionResponseDto } from './dto/decision-response.dto.js';
import { UpdateDecisionDto } from './dto/update-decision.dto.js';

const decisionRelations = {
  affectedMembers: true,
  eligibleMembers: true,
  previousRevision: true,
  rules: true,
  votes: true,
} as const;

@Injectable()
export class DecisionService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateDecisionDto): Promise<DecisionResponseDto> {
    return this.prisma.decision.create({
      data: data as unknown as Prisma.DecisionCreateInput,
      include: decisionRelations,
    }) as unknown as Promise<DecisionResponseDto>;
  }

  findAll(): Promise<DecisionResponseDto[]> {
    return this.prisma.decision.findMany({
      include: decisionRelations,
    }) as unknown as Promise<DecisionResponseDto[]>;
  }

  findOne(id: string): Promise<DecisionResponseDto | null> {
    return this.prisma.decision.findUnique({
      where: { id },
      include: decisionRelations,
    }) as unknown as Promise<DecisionResponseDto | null>;
  }

  update(id: string, data: UpdateDecisionDto): Promise<DecisionResponseDto> {
    return this.prisma.decision.update({
      where: { id },
      data: data as unknown as Prisma.DecisionUpdateInput,
      include: decisionRelations,
    }) as unknown as Promise<DecisionResponseDto>;
  }

  remove(id: string): Promise<DecisionResponseDto> {
    return this.prisma.decision.delete({
      where: { id },
      include: decisionRelations,
    }) as unknown as Promise<DecisionResponseDto>;
  }
}
