// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { assertEntityType } from '../surreal/entity-type.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';
import { CreateDecisionDto } from './dto/create-decision.dto.js';
import { DecisionResponseDto } from './dto/decision-response.dto.js';
import { UpdateDecisionDto } from './dto/update-decision.dto.js';

const relations = [
  {
    property: 'affectedMembers',
    table: 'member',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'eligibleMembers',
    table: 'member',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'previousRevision',
    table: 'decision',
    isArray: false,
    readOnly: false,
  },
  {
    property: 'rules',
    table: 'rule',
    isArray: true,
    readOnly: false,
  },
  {
    property: 'votes',
    table: 'vote',
    isArray: true,
    readOnly: false,
  },
] as const;

@Injectable()
export class DecisionService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateDecisionDto): Promise<DecisionResponseDto> {
    assertEntityType(data, 'Decision');
    return this.database.create('decision', data, relations);
  }

  findAll(): Promise<DecisionResponseDto[]> {
    return this.database.findAll('decision', relations);
  }

  findOne(id: string): Promise<DecisionResponseDto | null> {
    return this.database.findOne('decision', id, relations);
  }

  findRelations(
    id: string,
    query: RelationsQueryDto = {},
  ): Promise<RelationshipResponseDto[]> {
    return this.database.findRelations('decision', id, query);
  }

  update(id: string, data: UpdateDecisionDto): Promise<DecisionResponseDto> {
    assertEntityType(data, 'Decision', true);
    return this.database.update('decision', id, data, relations);
  }

  remove(id: string): Promise<DecisionResponseDto> {
    return this.database.remove('decision', id, relations);
  }
}
