// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { DecisionController } from './decision.controller.js';
import { DecisionService } from './decision.service.js';

@Module({
  controllers: [DecisionController],
  providers: [DecisionService],
})
export class DecisionModule {}
