// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import { SurrealService } from '../surreal/surreal.service.js';
import { CreateDelegationDto } from './dto/create-delegation.dto.js';
import { DelegationResponseDto } from './dto/delegation-response.dto.js';
import { UpdateDelegationDto } from './dto/update-delegation.dto.js';

const relations = [
  {
    property: 'permission',
    table: 'permission',
    isArray: false,
    readOnly: false,
  },
] as const;

@Injectable()
export class DelegationService {
  constructor(private readonly database: SurrealService) {}

  create(data: CreateDelegationDto): Promise<DelegationResponseDto> {
    return this.database.create('delegation', data, relations);
  }

  findAll(): Promise<DelegationResponseDto[]> {
    return this.database.findAll('delegation', relations);
  }

  findOne(id: string): Promise<DelegationResponseDto | null> {
    return this.database.findOne('delegation', id, relations);
  }

  update(
    id: string,
    data: UpdateDelegationDto,
  ): Promise<DelegationResponseDto> {
    return this.database.update('delegation', id, data, relations);
  }

  remove(id: string): Promise<DelegationResponseDto> {
    return this.database.remove('delegation', id, relations);
  }
}
