// Generated by scripts/generate-resource.mjs.
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBody,
  ApiBadRequestResponse,
  ApiCreatedResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import { CreateDelegationDto } from './dto/create-delegation.dto.js';
import { DelegationResponseDto } from './dto/delegation-response.dto.js';
import { UpdateDelegationDto } from './dto/update-delegation.dto.js';
import { DelegationService } from './delegation.service.js';
import { RelationsQueryDto } from '../surreal/relations-query.dto.js';
import { RelationshipResponseDto } from '../relationship/dto/relationship-response.dto.js';

@ApiTags('delegations')
@Controller('delegations')
export class DelegationController {
  constructor(private readonly delegationService: DelegationService) {}

  @Post()
  @ApiOperation({
    operationId: 'createDelegation',
    summary: 'Create a Delegation.',
  })
  @ApiBody({ type: CreateDelegationDto })
  @ApiCreatedResponse({ type: DelegationResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType must match the entity schema title.',
  })
  create(@Body() data: CreateDelegationDto): Promise<DelegationResponseDto> {
    return this.delegationService.create(data);
  }

  @Get()
  @ApiOperation({
    operationId: 'listDelegations',
    summary: 'List Delegation records.',
  })
  @ApiOkResponse({ type: DelegationResponseDto, isArray: true })
  findAll(): Promise<DelegationResponseDto[]> {
    return this.delegationService.findAll();
  }

  @Get(':id')
  @ApiOperation({
    operationId: 'getDelegation',
    summary: 'Get a Delegation by ID.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Delegation ID.' })
  @ApiOkResponse({ type: DelegationResponseDto })
  @ApiNotFoundResponse({ description: 'Delegation not found.' })
  async findOne(@Param('id') id: string): Promise<DelegationResponseDto> {
    const result = await this.delegationService.findOne(id);
    if (!result) throw new NotFoundException('Delegation not found.');
    return result;
  }

  @Get(':id/relations')
  @ApiOperation({
    operationId: 'listDelegationRelations',
    summary: 'Query relationships associated with a Delegation.',
  })
  @ApiParam({
    name: 'id',
    type: String,
    description: 'Delegation ID (URL-encode slashes).',
  })
  @ApiOkResponse({ type: RelationshipResponseDto, isArray: true })
  @ApiBadRequestResponse({
    description: 'Invalid direction or equality filters.',
  })
  @ApiNotFoundResponse({ description: 'Delegation not found.' })
  findRelations(
    @Param('id') id: string,
    @Query() query: RelationsQueryDto,
  ): Promise<RelationshipResponseDto[]> {
    return this.delegationService.findRelations(id, query);
  }

  @Patch(':id')
  @ApiOperation({
    operationId: 'updateDelegation',
    summary: 'Update a Delegation.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Delegation ID.' })
  @ApiBody({ type: UpdateDelegationDto })
  @ApiOkResponse({ type: DelegationResponseDto })
  @ApiBadRequestResponse({
    description: 'entityType cannot change from the entity schema title.',
  })
  @ApiNotFoundResponse({ description: 'Delegation not found.' })
  update(
    @Param('id') id: string,
    @Body() data: UpdateDelegationDto,
  ): Promise<DelegationResponseDto> {
    return this.delegationService.update(id, data);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    operationId: 'deleteDelegation',
    summary: 'Delete a Delegation.',
  })
  @ApiParam({ name: 'id', type: String, description: 'Delegation ID.' })
  @ApiNoContentResponse({ description: 'Delegation deleted.' })
  @ApiNotFoundResponse({ description: 'Delegation not found.' })
  async remove(@Param('id') id: string): Promise<void> {
    await this.delegationService.remove(id);
  }
}
