// Generated by scripts/generate-resource.mjs.
import { Module } from '@nestjs/common';
import { DelegationController } from './delegation.controller.js';
import { DelegationService } from './delegation.service.js';

@Module({
  controllers: [DelegationController],
  providers: [DelegationService],
})
export class DelegationModule {}
