// Generated by scripts/generate-resource.mjs.
import { Injectable } from '@nestjs/common';
import type { Prisma } from '../generated/prisma/client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { CreateDelegationDto } from './dto/create-delegation.dto.js';
import { DelegationResponseDto } from './dto/delegation-response.dto.js';
import { UpdateDelegationDto } from './dto/update-delegation.dto.js';

const delegationRelations = {
  permission: true,
} as const;

@Injectable()
export class DelegationService {
  constructor(private readonly prisma: PrismaService) {}

  create(data: CreateDelegationDto): Promise<DelegationResponseDto> {
    return this.prisma.delegation.create({
      data: data as unknown as Prisma.DelegationCreateInput,
      include: delegationRelations,
    }) as unknown as Promise<DelegationResponseDto>;
  }

  findAll(): Promise<DelegationResponseDto[]> {
    return this.prisma.delegation.findMany({
      include: delegationRelations,
    }) as unknown as Promise<DelegationResponseDto[]>;
  }

  findOne(id: string): Promise<DelegationResponseDto | null> {
    return this.prisma.delegation.findUnique({
      where: { id },
      include: delegationRelations,
    }) as unknown as Promise<DelegationResponseDto | null>;
  }

  update(
    id: string,
    data: UpdateDelegationDto,
  ): Promise<DelegationResponseDto> {
    return this.prisma.delegation.update({
      where: { id },
      data: data as unknown as Prisma.DelegationUpdateInput,
      include: delegationRelations,
    }) as unknown as Promise<DelegationResponseDto>;
  }

  remove(id: string): Promise<DelegationResponseDto> {
    return this.prisma.delegation.delete({
      where: { id },
      include: delegationRelations,
    }) as unknown as Promise<DelegationResponseDto>;
  }
}
